### ISSUE TITLE
Remove old Apple TV from Home Assistant

### ISSUE THREAD

**Issue by chris83ms** [postlund/pyatv#1102]
Hey,

I bought a new Apple TV and forgot to remove the old one before I resetted it. Now HA always wants to reconfigure the old device which isn't on the network anymore. I can't remove the old device in HA. Is there a trick to remove the old Apple TV?

To reproduce: Remove Old Apple TV from the network without removing it from HA. Connect new Apple TV and configure it. On every Restart HA keeps informing the "reconfigure dialog".

Expected behavior: Dialog to remove old device from config

System Setup: HA 2021.5.5 in Docker Container on a Fedora Host
Apple TV 4K (old one) with latest tvOS
Apple TV 4K (new one) with latest tvOS

Kind regards

Christian

P.S.: If I'd send you more information, please get in touch.

```log
If you are attaching a log, replace this text with the log (it will ensure proper formatting). Otherwise remove this section.
```
**To Reproduce**

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: [e.g. Debian]
 - Python: [e.g. 3.6.2]
 - pyatv: [e.g. 0.3.10]
 - Apple TV: [e.g. Apple TV 4K tvOS 13.4]

**Additional context**

**Comment by postlund** [comment]
Did you go into the Integrations page and remote it from there?

**Comment by chris83ms** [comment]
Hey Postlund,

there is no removal button:/

![9A8773B1-61D6-48D0-8B9C-1B66CD0B567E](https://user-images.githubusercontent.com/54248289/119339829-f6b0e500-bc91-11eb-8261-be31d6c3f7ee.jpeg)

**Comment by postlund** [comment]
Hmmm, if you press the button then it will start the config flow and try to re-auth? It doesn't appear anywhere else in the integrations page?

**Comment by chris83ms** [comment]
I can try to remove the new AppleTV. Perhaps this helps.

**Comment by postlund** [comment]
If there's no entry for the old Apple TV in the integrations page, like this one in the old UI:

<img width="273" alt="Skärmavbild 2021-05-24 kl  14 26 46" src="https://user-images.githubusercontent.com/5982179/119347657-1baa5580-bc9c-11eb-84de-a0189d7e26c2.png">

Then I would say it's a regression in the frontend

**Comment by chris83ms** [comment]
No, there isn‘t. I removed the new Apple TV, removed the integration, restarted HA, installed the integration. Now there‘s no Apple TV on the integrations Page…

When I try to add the Apple TV, it says: This Device is already configured.

**Comment by postlund** [comment]
I think there's some old junk left in the `core.config_entries`, not sure how that can happen. Can you take look in that file and see if the old Apple TV is there?

**Comment by postlund** [comment]
One reason I have found for this is when a config entry is loaded but an error (exception) occurs during the setup. That should never happen, exceptions should always be taken care of. But it might still happen if the config entry format is not compatible with the running version of the code. Should never happen, but... This issue is a bit old now and I'm trying to clean up old issues before they become stale. The solution (albeit a bit unfortunate) is the manually remove entries from `.storage/core.config_entries` and restart. Hopefully things will work better with the beta version of the integration (https://github.com/postlund/hass-atv-beta).

I will close the issue, please re-open if what I wrote above does not work or create a new issue.
