### ISSUE TITLE
RAOP: Password protected devices

### ISSUE THREAD

**Issue by Schlaubischlump** [postlund/pyatv#1159]
**What feature would you like?**
Support password protected devices when streaming using the RAOP protocol.

**Describe the solution you'd like**
To allow password protected devices it is necessary to first send an announce request which must fail with a 403 error code. The response body contains the necessary information required for the authentication. 

I plan to implement the following behaviour inside the `RtspSession`:

``` Python
def announce(self) -> HttpResponse:
    ....    
    try:
      await self.exchange(
          "ANNOUNCE",
          content_type="application/sdp",
          body=body,
      )
    except exceptions.AuthenticationError as error:
        # parse response
        # safe the authentication information as an RtspSession attribute
        # send a second announce request with the authentication information
...
# send all future requests with the authentication information
```

The actual code to parse, store and send the authentication information shouldn't be too hard to implement. I'm just not sure about how to best propagate the error. Currently the response is ignored by the `send_and_receive` method if a 401 or 403 error code is detected. It would be necessary to change the behaviour to somehow return the response body as well. Additionally  the `exchange` method would need to propagate the error too. 
There is already an `allow_error` flag, which does not allow 401 or 403 errors. Would it be a good idea to modify this flag ? Or should I introduce a second flag for 401, 403 error codes ? Or should I append the response to the `AuthenticationError` object ? 

**Any other information to share?**
No

**Comment by postlund** [comment]
I think that you can safely change it so that `allow_error` doesn't raise an `AuthenticationError`, shouldn't break anything from what I can see.

There's a few things to consider when implementing this, one being that there's no notion of "password" in pyatv. Mostly as I haven't decided how to add that, it kinda overlaps with pairing but also not... But let's just take the bull by it's horns. My suggestion for tasks to implement this (and you should probably take it in steps, even submit several PRs if you like):

1. Add a password field to `conf.RaopService` so we can store the password somewhere. Make it a property and implement a setter, so the user can fill it in.
2. Extend `scripts/atvremote.py` to take `--raop-password` and if it is passed, update the configuration with that. Should be similar to how credentials are handled.
3. Implement support for basic auth in `support/http.py` for both `HttpConnection` and `BasicHttpServer`. The first one is used for the client and the http server is used by the functional tests. There's a lot of documentation of basic auth, so it shouldn't be that hard to implement. One example is [Wikipedia](https://en.m.wikipedia.org/wiki/Basic_access_authentication).
4. Finally make implementation in RAOP, which should now be fairly easy as everything you need is now in place.

Making sure to add tests and documentation for everything is important as well. Feel free to ask questions regarding design, testing or whatever and I'll try to help you out (it takes a while to get used to a new code base).

**Comment by Schlaubischlump** [comment]
Regarding 3. 

Apples basic auth differs from the default implementation if I recall correctly. They send a nonce besides the realm and apply a couple of md5sums to the string concatenations. Do the other protocols require the "normal" baisc auth or is it safe to implement the Apple specific basic auth inside the http classes?

**Comment by postlund** [comment]
Right, it's Apple, of course they are doing something special. It's just AirPlay and RAOP that uses my custom HTTP implementation, so no one else rely on basic auth. But I would prefer to keep the abstraction and not add any Apple specific stuff there. I suggest that you do the client logic directly in `raop.py`, it's easy to extract headers and include your own in new requests. So should be pretty easy.

When it comes to the raop service in the fake device (`tests/fake_device/raop.py`) I would suggest that you override `handle_request` from `HttpSimpleRouter` in `FakeRaopService`. That's the method that gets all requests and dispatches them to the correct handler. You can add some logic here to check if password has been provided correctly, set a flag and  just forward all calls to the super class when the flag is set. Doing the check here is nice as it will catch all requests, so it would make it impossible to by-pass the password validation.

**Comment by Schlaubischlump** [comment]
I just wanted to let you know that I started to work on this. It's still missing the documentation and test cases, but the basic implementation seems to be working. For now I just tested it with shairport-sync. I'm still not that super familiar with the code structure, so I might need to refractor the code a little bit, after you looked at it. I will open a pull request when I have implemented the test cases and updated the documentation.

**Comment by postlund** [comment]
That sounds like a very good start! 👍 I'll have a look once you open a PR (and I have some time to spare). If you have any questions, just let me know.

The RAOP code is a bit messy right now, I'm trying to refactor along the way... Currently working on play/pause/stop, which adds a few new layers of complexity that will definitely require some re-structuring. But it's definitely towards a better, more general design.

**Comment by postlund** [comment]
@Schlaubischlump Just want to give some heads up that I will move modules around a bit soon (#1140), so I would recommend you try to open a PR when you can unless you want to deal with potential merge conflicts. I won't be doing this like...today, but at some point soon.

**Comment by Schlaubischlump** [comment]
Thanks for the heads up. I might have time to add the testcases and the documentation in the evening
