### ISSUE TITLE
push_updates : wrong status

### ISSUE THREAD

**Issue by MetaImi** [postlund/pyatv#124]
HI 

I'm checking the lib to integrate it on my pi for home automation. I have 2 Apple TV with latest tvOS. During the test, a video was playing via airplay from my mac from youtube. Here is the log: 

 atvremote push_updates --address 10.0.1.51 --login_id 00000000-110e-2165-db5a-61d3c9944002
Press ENTER to stop
Media type: Video
Play state: Paused
     Title: 
  Position: 250/1036s (24.1%)
    Repeat: Off
   Shuffle: False
--------------------
Media type: Video
Play state: Paused
     Title: 
  Position: 295/1036s (28.5%)
    Repeat: Off
   Shuffle: False
--------------------
Media type: Video
Play state: Paused
     Title: 
  Position: 296/1036s (28.6%)
    Repeat: Off
   Shuffle: False
--------------------

When I start the app, it immediately gives a paused state. Then I paused the video, then restarted it. A notification is received, but the info is wrong.

**Comment by postlund** [comment]
Hmm, this seems a bit odd. Can you try running again with the --debug flag?

**Comment by postlund** [comment]
Any update on this?

**Comment by postlund** [comment]
So, this is an interesting issue. The updates works correctly in the Remote app and that is likely because of MRP. But the DMAP implementation seems to be incorrect. The same behavior (as in pyatv) seems to also be present in the iTunes Remote app. So I believe that this is a problem with the ATV itself. If Apples own app shows the wrong thing too, I don't see that there is anything I can do about it I'm afraid. I will have another look, but my guess is that it is better that I focus on MRP instead.

**Comment by postlund** [comment]
Based on my previous investigation, this issue is within the DMAP implementation in the ATV itself. So not much I can do. Since DMAP is dropped
In tvOS 13, this only applies to old devices as well. So less and less of a problem. Closing issue now.
