### ISSUE TITLE
Apple TV network communication

### ISSUE THREAD

**Issue by TonyBrobston** [postlund/pyatv#1285]
Hello @postlund. First off, thanks for all the hard work you've done on this tool!

I was wondering if you could help me resolve an issue. I'm using the Apple TV integration in Home Assistant (https://www.home-assistant.io/integrations/apple_tv/). I'm running Home Assistant in docker, in a docker-compose (https://github.com/TonyBrobston/tbro-server/blob/a20e0e2a2b46c39c626f14a009aa42acb66008fa/home-automation/docker-compose.yml#L59-L63). 

When I run Home Assistant in `network_mode: host` (https://docs.docker.com/network/host/), everything works great; Home Assistant's autodiscovery finds the Apple TV, I configure it, a four digit number shows up on the Apple TV, I enter it into Home Assistant, and we're off to the races.

However, I'm hoping to not run Home Assistant in `network_mode: host`. When running my setup as it is in `tbro-server` (linked above), Home Assistant finds the Apple TV through autodiscovery and allows me to configure; however I can't get it to successfully configure and it also seems to take me down a different configuration path, it mentions something about `DMAP` service and instead of me entering a four digit number into Home Assistant, the integration gives me a four digit number to enter into the Apple TV, however the Apple TV never prompts me for the four digit number.

Here are some screenshots:
![discover](https://user-images.githubusercontent.com/4724577/132056491-f8eb4bd9-375e-405a-8207-201f2649d37f.PNG)
![confirm](https://user-images.githubusercontent.com/4724577/132056502-f9cd28a1-cc22-4000-af3b-de55a4f576da.PNG)
![pairing](https://user-images.githubusercontent.com/4724577/132056507-9bb81d7d-6d89-40bf-ba13-f0c2aa2dadd1.PNG)
![aborted](https://user-images.githubusercontent.com/4724577/132056510-6281be0f-e327-44c7-bd89-31eddf944219.PNG)

The issue seems to be related to the Apple TV communicating with my server vs. communicating with a container on my server (so network_mode: host vs. not). Normally the solution is to expose a few ports through port mapping (https://docs.docker.com/compose/compose-file/compose-file-v3/#ports). I've tried a ton of different ports, I was pretty confident that `3689` was going to be the correct port since `netdisco` finds this:

```
apple_tv:
[
   {
      "host":"[redacted]",
      "hostname":"Bedroom-Apple-TV.local.",
      "name":"Bedroom Apple TV",
      "port":3689,
      "properties":{
         "DFID":"2",
         "EiTS":"1",
         "MiTPV":"196611",
         "MniT":"167845888",
         "Name":"Bedroom Apple TV",
         "PrVs":"65538",
         "atSV":"65541",
         "fs":"2",
         "hG":"00000000-0676-516b-fee9-18bf0d90485c",
         "txtvers":"1"
      }
   }
]
```

Any ideas on what to try? I can also put together an example repo with a docker-compose that reproduces the issue if that helps.

Thanks!
Tony

**Comment by postlund** [comment]
Hey and thank you! 🙏 

Based on what you are writing, I guess you have an Apple TV 4 or later? They use the MRP protocol (for now) and require you to enter a 4 digit code to pair, just like you describe (AirPlay behaves in the same way, too). Older devices, like the Apple TV 3, but also iTunes and other iTunes compatible software, use DMAP instead. It was used on newer devices up until tvOS 13, where it was removed. So, can you confirm that it is in fact the same device that is actually found in both cases?

The problem here is two-fold, sort to say. Discovery seems iffy as it finds something, but is it the right thing? Getting multicast DNS (zeroconf) working in containers without using host mode sounds tricky to me. It uses UDP port 5353 anyway. As pyatv rely on this to work, it is very important that multicast traffic can pass through correctly. 

The protocols on the device uses various other ports, which you find in the zeroconf service for each protocol. DMAP always uses port 3689. AirPlay port 7000 (5000 for RAOP), but some third party devices use other ports. The remaining protocols use a free port (I.e. "random"). They are all outbound, so unless you filter outgoing traffic that shouldn't be a problem.

**Comment by TonyBrobston** [comment]
Based on my research I have an Apple TV 3, the model number is `A1469`. I also ran `docker exec [container id] python3 netdisco` both with `network_mode: host` and without, I got the same results for both, which is the `apple_tv` json structure above.

I am running an mDNS repeater to repeat the multicast from my host machine's network to my docker network; however I don't know that much about mDNS, so I'm not sure if that's "enough" to get things working properly. https://github.com/TonyBrobston/tbro-server/blob/a20e0e2a2b46c39c626f14a009aa42acb66008fa/home-automation/docker-compose.yml#L65-L71

I realize it probably seems like a round-about way of doing things; to run an mDNS repeater in `network_mode: host`, rather than just run Home Assistant as `network_mode: host`. My thought is that mDNS should really only do 1 thing and Home Assistant is capable of doing a lot of things. I see containers as a sort of firewall, if you are running without `network_mode: host` you can control exactly what holes are punched through the wall. However, this may be more work than it's worth; but it's worth a shot.

I'd be curious to open all the ports on my `home-assistant` container that you think might be needed and see what happens. If it successfully pairs, I'll remove ports until it breaks and that will tell me exactly which ports are needed. Unfortunately the "random" port situation makes things a but tricky. It is possible to specify a range of ports in docker, but if it is a large range, it takes forever to start up.

I think it's also worth mentioning that I have a lot of other devices that have been discovered and most all of them work well.

Thanks for the help!

**Comment by postlund** [comment]
Ok, so yes, it sounds reasonable that you have an Apple TV 3 as it uses DMAP. The pairing process is reversed for that protocol. The client (pyatv) sets up a web server on a random port and announce it on the network with the `_touch-remote._tcp.local` service. The Apple TV then looks for that service and connects back and here is the problem as I see it. First and foremost, the randomized port is a problem as that won't be open in the container and the address announced in the zeroconf service is likely the docker internal address, so that is also wrong. It's not really designed for that kind of use case.

But the pairing process only needs to be done once. Can't you run home assistant in host mode, add the integration and move it out of host mode again?

**Comment by postlund** [comment]
Did you manage to test my theory?

**Comment by TonyBrobston** [comment]
I can give that a try today. I've got it paired currently in host mode, I'll turn host mode off, and run things as I did before; I believe I've tried this and it hadn't worked, but I'll check again and report back.

**Comment by TonyBrobston** [comment]
I tested that I was able to use my remote in Home Assistant (which ultimately uses pyatv) to navigate around the Apple TV's interface, I then removed `network_mode: host` from my docker-compose and restarted (`docker-compose up -d`). Now when I try to navigate around the Apple TV's interface it does not respond.

**Comment by postlund** [comment]
What does the log say?

**Comment by TonyBrobston** [comment]
I'll take a look again today and post the logs up. Is this the correct way to log? https://www.home-assistant.io/integrations/apple_tv/#debugging

My home assistant instances is logging a ton of stuff so I'll probably `| grep` the logs for `pyatv` and post that up.

**Comment by postlund** [comment]
Yes, that should be correct. But you can start by looking in the log you find under Configuration in the frontend. You will probably find something there.
