### ISSUE TITLE
Sync Volume between two homepods

### ISSUE THREAD

**Issue by corrpel** [postlund/pyatv#1324]
### What's on your mind?

Hello,
I am trying to sync the volume between two homepods using pyatv, but when i use audio.volume i get 33.0 in python code.
I've tried on 0.8.2 and 0.9.0. I am not that good at writing code, but i used manual connect using ID and IP and raop protocol, from the example provided on github.
Can you please provide an example how to get and set the volume please, because when i use atvremote, the volume get and set are working correctly, and i think the problem is in the code i am writing.
I cannot use atvremote tool to execute it every 5 seconds because it is using too much resources on a raspberry pi.
Thank you!

**Comment by postlund** [comment]
You've hit one of the gotchas! RAOP only supports volume controls for the active stream, in case you are streaming something with `stream_file`. This is simply because that's how AirPlay works (and RAOP is just the audio streaming part of AirPlay). What you need to set up is the `airplay` protocol instead, which will enable MRP-over-AirPlay which can be used for proper volume management. I suggest that you base your code on one of the examples using scanning instead, that way it will be automatic (I.e. you don't have to do anything else). It will just work. It's almost as fast as manual connect anyways (especially when using unicast scanning), so there's little to no reason not doing that.

The stream example is a good base:

https://github.com/postlund/pyatv/blob/master/examples/stream.py

**Comment by corrpel** [comment]
Thanks! Seems like is returning the correct value using this example :)

**Comment by postlund** [comment]
I hope that it works 😄 

At some point, when I have implemented #1301, you will be able to get instant updates of volume changes from the device whenever it changes so you don't have to poll. I'm not there yet though.

**Comment by corrpel** [comment]
Nice! For me know, i am syncing only with push updates, but it whould be nice to update, but it would be very nice to have pushupdate for volume change. One more thing, i saw that when appletv is not playing, volume reported on homepod is 100.0. When playing, it is showing the real value. I think this is normal right?

**Comment by postlund** [comment]
Yeah, that would be the best solution.

Hmm, that sounds a bit strange. What is your set up? Can you check what iOS reports as volume for the HomePod? Sounds a bit strange that it would report 100%.

**Comment by corrpel** [comment]
Hmm,
I cannot reproduce it anymore now.
I’ve restarted the apple tv. I am running TVOS15, conected to two stereo homepod minis as default + one temporary output homepod mini. Maybe it is just that TVOS15 homepodos15 are two early…

**Comment by postlund** [comment]
Maybe it was some kind of fluke. Feel free to open the issue again if encounter it again.
