### ISSUE TITLE
atvremote : 2 commands pairing

### ISSUE THREAD

**Issue by NebzHB** [postlund/pyatv#1326]
### What feature would you like?

Hello,

as i'm using atvremote to pair in a web interface, a non-interactive pairing in 2 steps would be nice.

### Describe the solution you'd like

`atvremote -i id:id:id:id:id:id --protocol xxx beginpair` (exits when device_provides_pin)
(the atv display the pairing code, the user type the code in a web form)
`atvremote -i id:id:id:id:id:id --protocol xxx -p 1234 finishpair`

### Any other information to share?

or maybe it's already possible somehow ?

thank you in advance

**Comment by postlund** [comment]
It's technically not possible because as soon you close the connection, I.e. `atvremote` exits, the state is lost and you have to start pairing all over again. It would require a daemon of some sort and a client towards that daemon to accomplish, not anything I have plans to implement in `atvremote`.

**Comment by NebzHB** [comment]
ok thank you, i'll maybe use your example to make it a daemon...

**Comment by postlund** [comment]
That is probably the easiest solution. Should be fairly simple to achieve with the tutorial as base.
