### ISSUE TITLE
New Beta version finds non Apple TV related devices

### ISSUE THREAD

**Issue by Smiggel** [postlund/pyatv#1337]
### What to investigate?

I noticed that after installing the new beta version for iOS 15 selects other media devices in my network that are not apple related. For example, my Sonos Beam is suggested to HA as new device.

### Expected outcome

I was excepting the beta to only show my Apple TV 4K as device.

**Comment by postlund** [comment]
As mentioned in the README-file (in hass-atv-beta), the integration will now also find HomePods, instances of the Music app on macOS as well as all AirPlay receivers. More or less anything "Apple" (except for the fact that AirPlay is a licensed technology, so it can come from other manufacturers too).

This is possible simply because pyatv supports all of these devices and also has a generic API, so anything pyatv supports, Home Assistant also supports. I will leave it for evaluation to see if it accepted by users or not, otherwise I'll change it. Maybe it should be changed to a more "apple generic" integration. I don't know.

**Comment by Smiggel** [comment]
Ah ok. Clearly did not read the description correctly. That explains it. :-D Thanks!

**Comment by postlund** [comment]
Great! 👍 Will close this now.

**Comment by PDekker** [comment]
Hi @postlund Samsung TV errors our on "Unexpected error".

Do you need debug logs?

**Comment by postlund** [comment]
Hey @PDekker! Logs would be great! Start with the short one in Configuration -> log.

**Comment by PDekker** [comment]
`Exception in _async_connected when dispatching 'apple_tv_connected_D0:03:DF:24:81:1F': (<pyatv.core.facade.FacadeAppleTV object at 0x7fa79e207250>,) Traceback (most recent call last): File "/config/custom_components/apple_tv/__init__.py", line 135, in _async_connected self.async_device_connected(atv) File "/config/custom_components/apple_tv/media_player.py", line 91, in async_device_connected self.atv.push_updater.listener = self File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 485, in push_updater return self._interfacea[interface.PushUpdater].main_instance # type: ignore File "/usr/local/lib/python3.9/site-packages/pyatv/core/relayer.py", line 60, in main_instance raise exceptions.NotSupportedError() pyatv.exceptions.NotSupportedError`

**Comment by postlund** [comment]
Right, I see the issue here. The TV *only* supports the video part of AirPlay and the only thing I have implemented there is `play_url`. Because of that, there's no support for push updates and I didn't add any check for that so it gives the `NotSupportedError.. I will make sure to fix that, thanks for making me aware of that 👍
