### ISSUE TITLE
Playback time on video 

### ISSUE THREAD

**Issue by lorenzoCuevas** [postlund/pyatv#1349]
### What's on your mind?

Hi again,

I’m doing a personal project base on your API implementation of the apple tv and I’m trying to figure out on how to write a python “if statement” for the media playback time on the apple tv (video) base on the push updates method. I wonder if you could provide any example that would help me achieve this goal? Thanks!

**Comment by postlund** [comment]
Hey!

It depdends a bit on what you want to achieve. You will only get push updates when something actually change, but pyatv will not repeatedly call the listener you set up as the position changes (e.g. every second or so) as that would be very inefficient. You need to save a timestamp and calculate where in the stream you are based on current position and that timestamp. Maybe if you describe your use case a bit more, maybe I can provide a better example.

The base example is this one I guess:

https://github.com/postlund/pyatv/blob/master/examples/play_url.py

**Comment by lorenzoCuevas** [comment]
To describe more on my project, my goal is to dim the lights when the a movie is playing or paused using my smart light-bulb's API (Lifx) and your apple TV API. The push-updates method works perfectly bridging the functions of the light bulb and the apple TV by sensing whether the media is paused or playing. I'm wondering if it works the same way on monitoring the current time of a movie so the lights automatically dim up when the credits roll like the movie theaters.

here is the code:
import sys
import asyncio
import pyatv
from pyatv.interface import PushListener


class MyPushListener(PushListener):
    def playstatus_update(self, updater, playstatus):
         if playstatus.device_state == playstatus.device_state.Paused:
            print("Paused")
            from lifx import lifxDimUp
            lifxDimUp()
         elif playstatus.device_state == playstatus.device_state.Playing:
            print("Playing")
            from lifx import lifxDimDown
            lifxDimDown()
            

    def playstatus_error(self, updater, exception):
        print("Got an exception:", exception)


async def main():
    loop = asyncio.get_event_loop()

    atvs = await pyatv.scan(loop, identifier="50:32:37:9E:07:92")
    if not atvs:
        print("No device found", file=sys.stderr)
        return

    atv = await pyatv.connect(atvs[0], loop)
    listener = MyPushListener()
    try:
        atv.push_updater.listener = listener
        atv.push_updater.start()

        print("Press ENTER to quit")
        await loop.run_in_executor(None, sys.stdin.readline)
    except:
        atv.close()

Also, I have an issue connecting to my apple TV, here is the error that it gave from running the script:
usr/bin/python3 /home/pi/Downloads/pytatv2.py
Failed to set up remote control channel: HTTP/1.1 method POST failed with code 470: Connection Authorization Required
Traceback (most recent call last):
  File "/home/pi/Downloads/pytatv2.py", line 44, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/Downloads/pytatv2.py", line 31, in main
    atv = await pyatv.connect(atvs[0], loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/__init__.py", line 96, in connect
    await atv.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/core/facade.py", line 425, in connect
    if await setup_data.connect():
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/mrp/__init__.py", line 879, in _connect
    await protocol.start()
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/mrp/protocol.py", line 134, in start
    self.device_info = await self.send_and_receive(msg)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/mrp/protocol.py", line 234, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/mrp/protocol.py", line 242, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The name of the python script is pytatv2 by the way,
Thanks!!

**Comment by postlund** [comment]
Right, now I understand what you are trying to do. So I guess we have a few topics to address:

*1. Monitoring time for end credits*

As I mentioned in the previous post, there are no callbacks from pyatv when the position in the stream changes (generally). So you need to schedule a callback to be called at a specific time, that does whatever you need it to do. One way is to use `call_later` or `call_at` (https://docs.python.org/3/library/asyncio-eventloop.html#scheduling-delayed-callbacks). Basically you calculate either the timestamp or number of seconds until the end credits (something I leave up to you to decide how to do) and schedule a callback when something starts to play. You usually have `position` and `total_time` as a reference, but it depends on the app so you need to check the values. Remember to cancel the scheduled callback in case `device_state` moves from playing, otherwise you will get unexpected calls.

You can of course also set up a polling background task (e.g. `asyncio.create_task`) and manually poll the device state with some interval.

There are likely other 3rd party asyncio libraries that handles this in a nice way as well, but I don't know of any on top of my head. You can probably search on pypi in case you are interested.

*2. sync vs async*

I believe the lifx library you are using is synchronous, so you shouldn't call it from an async context (like the callback functions in your listener interface) as it will block the event loop while doing so. In asyncio, only one thing is executing at any given moment and if you run anything that takes a lot of time, then nothing else will run in the meantime. You need to use the executors for this.

```python
import lifx

async def dim_up():
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(None, lifx. lifxDimUp)

class MyPushListener(PushListener):
    def playstatus_update(self, updater, playstatus):
         if playstatus.device_state == playstatus.device_state.Paused:
            print("Paused")
            asyncio.create_task(dim_up())

```
This will create a background task that runs the `lifxDimUp` call in an executor. Maybe not the ideal solution, but should work.

*3. Timeout error* 

It's a bit unclear what happens here for the untrained eye 😉 But lets take the short gist... You need to pair with your device, save the credentials you get and restore them before connecting. If you want to keep it simple you can use `atvremote -s <ip> --protocol airplay pair` to get AirPlay credentials. You then insert the credentials you get using `set_credentials` like this:

```python
   ...
    atvs = await pyatv.scan(loop, identifier="")
    if not atvs:
        print("No device found", file=sys.stderr)
        return

    conf = atvs[0]
    conf.set_credentials(Protocol.AirPlay, "the_credentials_you_get_here")
    atv = await pyatv.connect(atvs[0], loop)
   ...
```

You have a programmatic example for pairing here:

https://github.com/postlund/pyatv/blob/master/examples/pairing.py

Some documentation as well:

https://pyatv.dev/development/scan_pair_and_connect/#pair
https://pyatv.dev/development/scan_pair_and_connect/#restoring-credentials

**Comment by lorenzoCuevas** [comment]
Thanks for the info, I'll comment back if I have future issues or questions!

**Comment by lorenzoCuevas** [comment]
Hi again,
for the connection issues to my apple TV, I've received the credentials for it and implemented the code that you have shown me to set the credentials into the pytatv2 script. But when I run it, it returned nothing.

Here's what it showed me on the console:
pi@raspberrypi:~ $ /usr/bin/python3 /home/pi/Downloads/pytatv2.py
pi@raspberrypi:~ $ 

And here is my code so far:
import sys
import asyncio
import pyatv
from pyatv.const import Protocol
from pyatv.interface import PushListener

class MyPushListener(PushListener):
    def playstatus_update(self, updater, playstatus):
         if playstatus.device_state == playstatus.device_state.Paused:
            print("Paused")
            from lifx import lifxDimUp
            lifxDimUp()
         elif playstatus.device_state == playstatus.device_state.Playing:
            print("Playing")
            from lifx import lifxDimDown
            lifxDimDown()
            

    def playstatus_error(self, updater, exception):
        print("Got an exception:", exception)


async def main():
    loop = asyncio.get_event_loop()

    atvs = await pyatv.scan(loop, identifier="50:32:37:9E:07:92")
    if not atvs:
        print("No device found", file=sys.stderr)
        return
    conf = atvs[0]
    conf.set_credentials([Protocol.AirPlay, "credentials here"])
    atv = await pyatv.connect(atvs[0], loop)
    listener = MyPushListener()
    try:
        atv.push_updater.listener = listener
        atv.push_updater.start()

        print("Press ENTER to quit")
        await loop.run_in_executor(None, sys.stdin.readline)
    except:
        atv.close()


    if __name__ == "__main__":
      asyncio.get_event_loop().run_until_complete(main())

I wonder if I'm doing something wrong if so show me where or what it is
