### ISSUE TITLE
When using stream_file, device state is stopped on Homepod Mini

### ISSUE THREAD

**Issue by popularsizzle** [postlund/pyatv#1358]
### Describe the bug

I'm streaming an audio file to a Homepod Mini, using the following:

`atvremote -s 192.168.1.22 stream_file=foo.mp3`

And following the status updates using:

`atvscript -s 192.168.1.22 playing | jq`

Despite the audio playing as expected, the Homepod `device_state` is **stopped**. Before the audio is streamed, the state is **idle** (and it returns to this state after the track finishes).

Further, when asking Siri to "stop" or "pause", it advises nothing is playing (despite the audio still being heard).

### Error log

Before playing:

```json
{
  "result": "success",
  "datetime": "2021-09-30T20:18:25.099140+10:00",
  "hash": "ca496c14642c78af6dd4250191fe175f6dafd72b4c33bcbab43c454aae051da1",
  "media_type": "unknown",
  "device_state": "idle",
  "title": null,
  "artist": null,
  "album": null,
  "genre": null,
  "total_time": null,
  "position": null,
  "shuffle": "off",
  "repeat": "off",
  "series_name": null,
  "season_number": null,
  "episode_number": null,
  "app": "AirMusic",
  "app_id": "com.apple.Music"
}
```

While playing:

```json
{
  "result": "success",
  "datetime": "2021-09-30T20:18:41.700195+10:00",
  "hash": "35D2FF07-3C6D-44AE-AB4C-7A5C79840E10",
  "media_type": "music",
  "device_state": "stopped",
  "title": "Idiot Oracle",
  "artist": "Paul Dempsey",
  "album": "Strange Loop",
  "genre": null,
  "total_time": 245,
  "position": 245,
  "shuffle": "off",
  "repeat": "off",
  "series_name": null,
  "season_number": null,
  "episode_number": null,
  "app": "Spotify",
  "app_id": "com.apple.tvairplayd"
}
```

After playing:

```json
{
  "result": "success",
  "datetime": "2021-09-30T20:18:51.643956+10:00",
  "hash": "ca496c14642c78af6dd4250191fe175f6dafd72b4c33bcbab43c454aae051da1",
  "media_type": "unknown",
  "device_state": "idle",
  "title": null,
  "artist": null,
  "album": null,
  "genre": null,
  "total_time": null,
  "position": null,
  "shuffle": "off",
  "repeat": "off",
  "series_name": null,
  "season_number": null,
  "episode_number": null,
  "app": "AirMusic",
  "app_id": "com.apple.Music"
}
```

### How to reproduce the bug?

Use pyatv to stream audio to a Homepod Mini.

### What is expected behavior?

The Homepod should think it's playing audio, and indicate so when polled.

### Operating System

macOS

### Python

3.9

### pyatv

0.9.2

### Device

Homepod Mini

### Additional context

I have tried using stable, and latest commit. Same outcome.

**Comment by postlund** [comment]
I can acknowledge both issues. The first one, device state being wrong, might be because I'm reporting wrong timestamps for metadata, but I'm not sure. The same problem exists if you look via the media player widget in control center.

The second issue probably has to do with that I don't support events from the receiver. The receiver (Apple TV) is supposed to send events back to the sender (pyatv) for playback controls, but I have not implemented that channel (not sure how it works).

**Comment by popularsizzle** [comment]
Regarding the first issue, are you planning on fixing this? Are you able to give some more information about what is wrong so others can have a look into it?

As for the second issue, it seems that even if this project did handle receiving events, the Homepod does not think it's playing, so is not likely to send any.

**Comment by postlund** [comment]
My intention is to fix both issues, of course. I want things to work. It's all about priority as I have a lot of things going on right now (being the only developer right) and getting the Home Assistant integration updated is at the top. But I can take a quick look at the position thing too.

It's supposed to say where in the stream we currently are, but there's probably something wrong with it. 
I don't know what the rules are regarding that (should be part of the AirPlay specification I guess), but I would expect it to send those kinds of event regardless and let the sender deal with carrying out the action.

My main suspect for the position issue is this:

https://github.com/postlund/pyatv/blob/65b40bd2d8df81a479b36e3dfaae54e88d56089f/pyatv/protocols/raop/raop.py#L549

The main reason I'm suspecting this is because MRP reports a bogus time like this:

```
  playbackQueue {
    location: 0
    contentItems {
      identifier: "55850A66-1BDD-47BE-842E-24EE455833C4"
      metadata {
        ...
        elapsedTime: -9501.00986394558
        ...
      }
    }
  }
```

I however know that other sender, like owntone, has the same problem. So I'm not sure.

**Comment by popularsizzle** [comment]
No problem.

I believe owntone has both [progress](https://github.com/owntone/owntone-server/commit/8368ca76867eb5e3bb59b90c8dae5d685a171430) and [events](https://github.com/owntone/owntone-server/commit/b6835fac2980334321bdde706fcf91305a736dd2) working.

**Comment by postlund** [comment]
That is for AirPlay v2 though, I only support v1 for streaming so far.

**Comment by postlund** [comment]
Can you re-try with 0.9.3?

**Comment by popularsizzle** [comment]
It seems to have regressed a little. I'm on 0.9.5 and getting the following error:

```
2021-10-16 18:34:48 ERROR [pyatv.protocols.raop.raop]: Audio error received: [Errno 55] No buffer space available
2021-10-16 18:34:48 WARNING [pyatv.protocols.raop.raop]: Connection closed while streaming audio
```

I tried a few times, and occasionally it would play for a few seconds. Not long enough for me to check out the *device_state* and *position* though. When this happens, the following would show in the output (in addition to the above):

```
2021-10-16 18:37:26 ERROR [pyatv.core.protocol]: Heartbeat 6 failed after 2 tries (AirPlay:192.168.1.20)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/protocol.py", line 36, in heartbeater
    await sender_func(message)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/remote_control.py", line 75, in _send_feedback
    await self.rtsp.feedback()
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/rtsp.py", line 221, in feedback
    return await self.exchange("POST", uri="/feedback", allow_error=allow_error)
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/rtsp.py", line 258, in exchange
    resp = await self.connection.send_and_receive(
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/http.py", line 381, in send_and_receive
    raise RuntimeError("not connected to remote")
RuntimeError: not connected to remote
```

Let me know if you need a more verbose log.

**Comment by postlund** [comment]
I believe the issue is addressed.
