### ISSUE TITLE
Background image not shown on Danish DR stations

### ISSUE THREAD

**Issue by Bluhme1** [postlund/pyatv#1364]
### Describe the bug

Running Homeassistant 2021.10.b1

Custom_component newest version

Background image not shown on Danish DR stations but shown when playing TV2 and Netflix. I remember that, that was also the case in the early phases of the development.

Does DR use another protocol?

### Error log

No error log

### How to reproduce the bug?

Starting a programme

### What is expected behavior?

Background image on the Lovelace Card

### Operating System

Homeassistant 2012.10.b1

### Python

Other

### pyatv

0.9.2

### Device

Apple TV 4K TVOS15

### Additional context

None

**Comment by postlund** [comment]
Does it show artwork in the widget in control center (or Lock Screen)? Maybe it doesn't have any? Otherwise I need debug logs from when the app is playing something to investigate.

**Comment by postlund** [comment]
Did you verify this? I suspect it's a problem with the app.

**Comment by postlund** [comment]
That might very well be the case. I usually look at my iPhone to see if any metadata or artwork is present there (if not, then it most likely isn't available). I can also look at the logs, if you provide me with some. But it's pretty likely that artwork isn't available in that particular case, since it works for other media.

**Comment by postlund** [comment]
Can you verify the behavior according to what I wrote above?

**Comment by postlund** [comment]
I suspect we can close this now. Feel free to re-open.
