### ISSUE TITLE
hass-atv-beta discovery finds anything that is AirPlay, including Sonos speakers

### ISSUE THREAD

**Issue by maddox** [postlund/pyatv#1374]
### Describe the bug

I'm not clear if this is the right place for bug reports or feedback on the hass-atv-beta, but issues are turned off on that repo.

After adding the custom component and restarting hass, I can see that discovery has found all of my Apple TVs. But it also discovered Sonos speakers that support AirPlay.

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/260/136122692-b828f20b-8b60-4df7-ac98-a2dffbf2fbae.png">

### Error log

```log
<place log here>
```

### How to reproduce the bug?

Use the hass-atv-beta

### What is expected behavior?

Discovery of just Apple TVs.

### Operating System

Linux

### Python

Other

### pyatv

0.9.2

### Device

Apple TVs

### Additional context

There is no additional context.

**Comment by postlund** [comment]
Issues should be reported here, as stated in the readme for the component 😉 

And yes, the component has been generalized to support anything that pyatv supports, including any AirPlay receivers. Support is very basic right, so you can more or less only stream audio to most devices but more support will come over time. So it is expected behavior.
