### ISSUE TITLE
Is it possible to support “Intercom” feature of HomePod?

### ISSUE THREAD

**Issue by ha0y** [postlund/pyatv#1381]
### What's on your mind?

Initially, thank you for your great work and instant reply on issues. I’m not sure if this feature request is applicable here, please forgive me if it doesn’t.

I found the intercom feature of HomePod really helpful. It can broadcast short voice messages without interrupting the playing music. It will be great if we can integrate it into Home Assistant, so we can use it for custom notification.

I’ve managed to capture some packets when using intercom from my iPad to HomePod. But I have no idea on how to parse them. So I will put them here. These are two voice messages, where `192.168.0.183` is my iPad and `192.168.0.212` is my HomePod mini.

[intercom.zip](https://github.com/postlund/pyatv/files/7312020/intercom.zip)

**Comment by postlund** [comment]
I have never used the intercom feature myself, but I can see it being handy. It is handled by the Companion protocol, which is encrypted, so the traffic logs are unfortunately not very useful because of that. Another issue, which might be the biggest one right now, is that I don't know any way to pair Companion with a HomePod. So even though support for the protocol is in place, and perhaps I could reverse engineer the intercom part, there's no way to use it as it's not possible without any credentials (which is obtained via pairing). I do like the idea, but it's technically not possible right now at least.

**Comment by ha0y** [comment]
Thank you for your reply. It is very useful information. This also explains why intercom is not available on Mac. Hope the Companion will be supported one day.

**Comment by JonLaliberte** [comment]
Hey @postlund. I assume nothing has changed here in terms of access to the protocol?
I had a scary idea of a mix of Home Assistant and Shortcuts on Mac to make use of the Intercom feature, then I saw this bummer:
<img width="310" alt="Screenshot 2023-08-15 at 5 15 29 PM" src="https://github.com/postlund/pyatv/assets/5403662/2db5d32a-bbf8-43ce-9fd7-003c073702df">

**Comment by postlund** [comment]
@JonLaliberte It has not changed, still have no idea how to solve pairing. Someday maybe, but at least not right now.
