### ISSUE TITLE
Identifier is missing

### ISSUE THREAD

**Issue by fidesachates** [postlund/pyatv#1410]
### What's on your mind?

I'm not sure if this is a bug or I'm not using the library as intended hence this is a question and not a bug report. 

I've noticed that since the switch to Companion, the connection does not live very long. I seem to have to connect after even seconds of inactivity otherwise the command doesn't do anything. I'm changing my code to work around this by basically calling connect on every command (although ideally we'd have a way to check if we need to reconnect or have a longer living connection). 

I tried to save the outcome of the scan (interface.BaseConfig) so I don't have to scan each time, but noticed something odd; when I tried to call connect on the saved `BaseConfig` on the second attempt, it said there was no identifier. After debugging it, it seems the `pyatv.connect()` method [adds the protocol MRP to services](https://github.com/postlund/pyatv/blob/v0.9.5/pyatv/protocols/airplay/__init__.py#L232) inside `interface.BaseConfig`. This means that if you call connect again, the identifier is `None` because [the loop assumes the first service has an identifier](https://github.com/postlund/pyatv/blob/v0.9.5/pyatv/interface.py#L1074-L1077). 

I'm on TvOs 15 and pyatv 0.9.5.

**Comment by fidesachates** [comment]
Was able to work around this by doing a deep copy of the `BaseConfig` object before calling connect and storing that. Though I feel like I'm writing hacks on hacks... would like some advice and guidance here.

**Comment by fidesachates** [comment]
Not sure what parts of the code you're interested in; let me know if this isn't what you had in mind. Below is code from a method I call before all operations. Excuse the poor syntax; python is not my forte. 

```
    if doScan:
        app.logger.info("Scanning")
        atvs = await scan(loop, hosts=['insert ip address of my apple tv'])
        app.logger.info("Scanning finished")
        if len(atvs) != 1:
            //TODO use the stored object if it exists
            raise Exception("Apple TV scan did not have our TV")

        scanned_atv = copy.deepcopy(atvs[0])
        scanned_atv.set_credentials(Protocol.Companion,'insert my credentials')
        scanned_atv.set_credentials(Protocol.AirPlay, 'insert my credentials')

    temp = copy.deepcopy(scanned_atv)
    atv = await connect(temp, loop)
```

**Comment by fidesachates** [comment]
> I'm interested in the "connection does not live very long" issues.

What I'm experiencing is if I don't call `pytav.connect(), in a few minutes things stop working. Though to be fair, I quickly wrote the workaround so the number of data points is pretty small. I can spin up a dev controller and confirm for you and get some logs if you wish. 

> A connection is established when a function that uses Companion is called and then torn down again. This will be changed by #1373 once I get that ready.

So I shouldn't need to call connect more than once?

>  So, firstly I need to know what functions you are using, what error you get and whatyou do with the object you get from connect?

For testing purposes, I called the get apps function twice. First time, it works and second time, I get an identifier is missing error (as a reminder I had changed my code to call connect on every function) so the error that's being thrown [is this one](https://github.com/postlund/pyatv/blob/578166567dcd9e3042f18a29cc28f2f568005e97/pyatv/__init__.py#L79-L80). And as I explained above, identifier is None because of the dummy MRP service. 

> Also, do you implement a DeviceListener to get updates on when the connection is closed (and a potential exception)?

Yes I have a Device Listener, but I don't think I've ever seen the hook get invoked. 

> What I don't understand though is how you get an error regarding "no identifier", that shouldn't happen since you have AirPlay in place. Can you print the config object before calling connect when this happens? That way we can see backtrack.

So this happens because I'm calling connect on the same config object over and over again. The problem is that on the second call, the config object now has the dummy MRP service and that service has no identifier. And [here](https://github.com/postlund/pyatv/blob/v0.9.5/pyatv/interface.py#L1074-L1077), you're returning the first identifier of the first not null service without checking if the identifier is None. 

I'm getting the distinct impression that the root cause of all this is my workaround code that calls connect on every function call. I feel like I shouldn't be calling connect on every function, but again I'm doing this because after a while, no function calls work without a reconnect and there's no way to tell when the connection was dropped because as I said, the device listener I wrote is never triggered. If all this smells of me using the library incorrectly, let me know and I'll dive into it on my side over the weekend.

**Comment by postlund** [comment]
> What I'm experiencing is if I don't call `pytav.connect(), in a few minutes things stop working. Though to be fair, I quickly wrote the workaround so the number of data points is pretty small. I can spin up a dev controller and confirm for you and get some logs if you wish.

The lifetime of an object you get from `connect` is typically until you get an exception from one of the interface methods or a callback to your DeviceListener. In that case you shall throw away your current connected instance and start over again.

If a connection is lost for some reason, it is indicated via the DeviceListener. However, for protocols not maintaining a persistent connection that will not work. Support for that in Companion will be merged very soon though. So, you should go by the convention of re-connecting whenever you get an exception from the methods you are calling (more or less what you are doing). What is interesting however is what, more specifically, stops working? What errors do you get? Any logs would help as this should normally not happen and it's either because of some usage error or a bug in pyatv (not very unlikely). So that's what I would like to figure out.

> So I shouldn't need to call connect more than once?

That is correct. It should only be needed in case of a problem or if the connection is lost, I.e. when restarting the device (which I don't classify as an error).

> For testing purposes, I called the get apps function twice. First time, it works and second time, I get an identifier is missing error (as a reminder I had changed my code to call connect on every function) so the error that's being thrown [is this one](https://github.com/postlund/pyatv/blob/578166567dcd9e3042f18a29cc28f2f568005e97/pyatv/__init__.py#L79-L80). And as I explained above, identifier is None because of the dummy MRP service.

Yeah, I need the error from when you don't call connect multiple times. Otherwise I can't see what's wrong.

> > Also, do you implement a DeviceListener to get updates on when the connection is closed (and a potential exception)?

Then it's probably a problem with Companion you are facing, likely a bug, as the DeviceListener isn't used there yet.

> So this happens because I'm calling connect on the same config object over and over again. The problem is that on the second call, the config object now has the dummy MRP service and that service has no identifier. And [here](https://github.com/postlund/pyatv/blob/v0.9.5/pyatv/interface.py#L1074-L1077), you're returning the first identifier of the first not null service without checking if the identifier is None.

Ah, you are right! That is a brain fart on my end, assuming MRP always has a unique identifier (which it normally does). That's another bug to add to the list!

> I'm getting the distinct impression that the root cause of all this is my workaround code that calls connect on every function call. I feel like I shouldn't be calling connect on every function, but again I'm doing this because after a while, no function calls work without a reconnect and there's no way to tell when the connection was dropped because as I said, the device listener I wrote is never triggered. If all this smells of me using the library incorrectly, let me know and I'll dive into it on my side over the weekend.

Exactly, you shouldn't. But things get a little intricate with the protocols not maintaining a persistent connection. Otherwise you should just follow the flow described in the beginning. Things are improving over time to make the interface more polished and well-defined. I've not managed to go all the way there yet, but getting closer every day. I actually appreciate that you opened this issue as some of the things I already know, but I sort of let them slide since no one has reported them before. But I actually do want to fix the interface and make "core" in pyatv really stable.

**Comment by postlund** [comment]
All of this should have been fixed on `master`.
