### ISSUE TITLE
Pyatv + Siri Remote Integration?

### ISSUE THREAD

**Issue by xpnewmedia** [postlund/pyatv#1411]
### What feature would you like?

Integrate library or Airplay in general, with Siri Remote for Apple TV, the physical device.

### Describe the solution you'd like

Somehow execute library's API using Siri Remotes bluetooth connection.

Whether to control other things and/or with the Apple TV.

Using voice commands to execute Pyatv and Airplay functions.

### Any other information to share?

Anyway there's a interface or mashup between these technologies?
pyatv, airplay technology and the Siri Remote.

**Comment by hokiebrian** [comment]
Not OP, but being able to programmatically send Siri commands to the ATV (or HomePod). As a reference, the Alexa Media Player (https://github.com/custom-components/alexa_media_player) allows sending any string and it is functions the same as a voice command (I believe that is talking to Alexa API and not the device directly though). Example use case - I use the Alexa component coupled with Apple Music API to generate my Playlists, Stations, etc. and when I select one, it sends "play XXXXX on Apple Music" to the designated Echo. I also have a freeform entry, I could type "tell me a joke" and Alexa will respond to that. Ideally, I'd love to use ATV (or HomePod) with this functionality and ditch the Echo. Since the ATV supports Siri commands via the remote, is there a way to mimic that process by sending a string to the ATV?

**Comment by postlund** [comment]
There's already an issue for that, #170, and I think someone managed reverse it. Shouldn't be that hard I guess but it would require a voice synthesizer that generates the voice that is good enough for Siri to understand. It's a cool feature but currently not something that is a priority for me personally (way too much in the backlog right now).

**Comment by postlund** [comment]
I believe the hardware interaction implied by this issue is out of scope for pyatv, will close issue.
