### ISSUE TITLE
Advertised IP in autodiscover/pairing process

### ISSUE THREAD

**Issue by jdebardi** [postlund/pyatv#143]
I think this may explain the 'flakiness' some people see.

My server has 2 local IP interfaces;
10.11.12.108
10.8.0.1

When doing for example a pairing, the atvremote sends out MDNS Answers with both local IP's, and depending on which one the ATV picks (which is random based on the timing) it will either pair, or not!

Here is a PCAP of a pairing exchange http://goml.jdbtelecoms.co.uk/wrong_ip_mdns.pcap

In Packets 8-13 atvremote advertises the 10.11.12.108 IP (which is the one I want it to). This makes sense as it is the source IP of the packet.

In Packets 30-37 it advertises the 10.8.0.1 IP (which is wrong!). This IP is a totally different interface on the server and should not be appearing here.

In Packet 41 the ATV attempts to respond, but as the last Answer it got contained 10.8.0.1 the address it sends in it's Answer is 10.8.0.1, and atvremote ignores it (or maybe a lower later IP stack drops it as it arrives on the 10.11.12.108 interface).

I think the fix is for atvremote to only include MDNS Answers with the IP address=Source IP of the packet, but it would also be nice to have a bind/answer IP option I guess.

**Comment by postlund** [comment]
Great observation, thanks for looking into this! I use an external library, python-zeroconf, for the mDNS part so I cannot answer for how it works. But I don't really understand the issue, it must be some logical problem in python-zeroconf in that case. The main idea is to discover services on all interfaces with local IP address (RFC1918). So that you have multiple interfaces should not matter, it should try to discover services on both networks independently. IMHO zeroconf should not (by default) have to be bound to a specific interface, those details should be hidden from the user.

I did have some issues with this in the pairing process, where I published the local web server on "one" of the local interface. In some cases this was not the one where the Apple TV was. But I fixed that, you can have a look in `pyatv/DMAP/pairing.py`.

If you have the time to look into this and propose a fix I would be more than happy! This is a known problem but I don't feel I have the time to look into it.

**Comment by postlund** [comment]
This issue is old now, I use a different library for zeroconf and nobody else have reported any problems since this issue was opened. So I'm closing it now, if the problem persists this issue can re-opened or a new created.
