### ISSUE TITLE
cannot import name 'ATTR_CONNECTIONS' from 'homeassistant.const' 

### ISSUE THREAD

**Issue by akballow** [postlund/pyatv#1431]
### Describe the bug

Logger: homeassistant.setup
Source: setup.py:178 
First occurred: 21:56:29 (1 occurrences) 
Last logged: 21:56:29

Setup failed for apple_tv: Unable to import component: cannot import name 'ATTR_CONNECTIONS' from 'homeassistant.const' (/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/const.py)

### Error log

```log
Logger: homeassistant.setup
Source: setup.py:178 
First occurred: 21:56:29 (1 occurrences) 
Last logged: 21:56:29

Setup failed for apple_tv: Unable to import component: cannot import name 'ATTR_CONNECTIONS' from 'homeassistant.const' (/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/const.py)
```

### How to reproduce the bug?

install 1.7 on HACS

### What is expected behavior?

loading, vs not loading?

### Operating System

Truenas 

### Python

3.8

### pyatv

?

### Device

Doesn't matter

### Additional context

Is there a way to downgrade back to 1.6?

**Comment by curt7000** [comment]
Unfortunately, it is still listing 2021.11.0 as a requirement.  I can't roll back to 1.6

**Comment by postlund** [comment]
I have removed the required version altogether from the repo and also made a new release (did that yesterday), so I don't know why HACS aren't picking that up.

**Comment by postlund** [comment]
This issue will kind of fix itself today when the new release comes out. I will push a new update with review changes from PR to core, which reverts config entry version back to 1 again. This yields better back- and forward compatibility when switching Home Assistant versions and resolve the issue many people have seen (about key "identifiers" not found). It however forces everyone running current version to remove all devices again and re-add them. This should hopefully be the last time and is mainly because I didn't quite understand how config entry versions was supposed to be used. It will be less painful this time as everything will load properly and devices can be removed from the integrations page (no fiddling in `.storage`).

There are only a few minor things left before things can be merged back to core, waiting for another PR being one of them. But hopefully this will happen really soon. It's still the matter of TTS that isn't solved yet though.

**Comment by postlund** [comment]
Fixed.
