### ISSUE TITLE
TTS in 2.1.0 immediately crashes HA 2021.12.1

### ISSUE THREAD

**Issue by steve28** [postlund/pyatv#1528]
### Describe the bug

I tried TTS tonight for the first time to my HomePod mini.  Since the crash is immediate, there is no log... not sure what else I can do.

I open the media player entity, type some text in the "Text to speak" line and press the button.  HA immediately crashes an restarts

I tried on two different HomePods as well.

### Error log

```log
<place log here>
```

### How to reproduce the bug?

open the media player entity, type some text in the "Text to speak" line and press the button.  HA immediately crashes an restarts

### What is expected behavior?

No crash

### Operating System

HomeAssistant OS

### Python

3.9

### pyatv

Whatever comes with v2.1.0

### Device

HomePod mini 15.1.1

### Additional context

```
Version | core-2021.12.1
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.83
CPU Architecture | x86_64
```

**Comment by postlund** [comment]
This is a problem with the `miniaudio` library that some people seem to hit. My theory is that the library is compiled with optimization flags that potentially uses instructions that are not supported by the CPU you are using. For reference, what CPU do you have? Solution to most people seems to be to re-install `miniaudio` manually, but that shouldn't be necessary.

**Comment by postlund** [comment]
I wrote a comment about it here: https://github.com/irmen/pyminiaudio/issues/42#issuecomment-993218604

**Comment by PeterHaban** [comment]
I've got the same problem, I'm running HassOS in a VM off VirtualBox on a host with Ubuntu 20.04.3 and Intel Celeron J3455.

**Comment by nikdoof** [comment]
Same issue, Kubernetes hosted on RHEL8 / vSphere 7 on Intel Ivy Bridge.

I suspect its down to the `-march=native` more than `-mtune=native`, as from what I've read tune targets the processor for optimisations but should still operate on older arches, where as arch could potentially generate backwards incompatible code.

**Comment by steve28** [comment]
> For reference, what CPU do you have? 

I'm running the Homeassistant OS in a VM on an intel NUC.  It seems about 2/3 of users are running HassOS... does that mean we'd need to file a bug/request in for that?  

FWIW, I can use the HA API directly and get the mp3 audio file and play it directly in a browser.

**Comment by Fannangir** [comment]
@postlund , I have the same issue, your assumption is correct, it is related to miniaudio.
Running HASSOS on a synology, under a VM.
Done the following in the homeassistant container to reinstal miniaudio.

apk update
apk add build-base
pip3 uninstall --yes miniaudio
pip3 install miniaudio

Restarted after installation, TTS works.

Just one comment, not related, maybe some improvement. Can you make it continue of a payback (if it was playing) instead of returning to pause mode?

Thanks.

**Comment by postlund** [comment]
@steve28 I've already written about the problem in the issue I linked to above. We'll take it from there, but it certainly needs attention.

@Fannangir Yeah, I'm pretty sure it's because of optimizations that use CPU instructions that are only available on newer models. I guess that you are after announcements that resumes what was previously playing? Not possible to do via AirPlay like this AFAIK. There's a speech API available via Companion that can do that via Siri. But I have no idea how that works and no way of getting Companion credentials that would allow me to do that even if I knew how it worked.

**Comment by Fannangir** [comment]
Understood.
Will check the option of a simple automation to resume playback following TTS announcement.
Thanks.

**Comment by steve28** [comment]
> apk update
apk add build-base
pip3 uninstall --yes miniaudio
pip3 install miniaudio

@Fannangir I assume this gets wiped every update.  Is there a way to make this happen automatically?

**Comment by Fannangir** [comment]
@steve28 correct. Unfortunately I do not have a solution as well.

**Comment by postlund** [comment]
This must be fixed in pyminiaudio to have a permanent fix. I created an issue for it, https://github.com/irmen/pyminiaudio/issues/43, hopefully we can sort it out there. It will likely take a while until this is fully resolved.

**Comment by postlund** [comment]
This problem should be fixed by the next version of pyminiaudio, so we will have to wait for that. Once it is out, I will make a new pyatv release, bump it in core and after that it should work as expected. I will update the issue when we are there.

**Comment by nikdoof** [comment]
pyminiaudio 1.46 is now been [released](https://github.com/irmen/pyminiaudio/releases/tag/v1.46) with the fixes.

**Comment by postlund** [comment]
I will bump minimum required version in the next release of pyatv and hopefully we can put this problem behind us after that.

**Comment by Dodoooh** [comment]
looks like it' s finally fixed! :)  at least it works for me. THANKS A LOT

**Comment by SalkinDK** [comment]
Works for me as well thank you so much!! @postlund

**Comment by postlund** [comment]
Yep, should be fixed 👍
