### ISSUE TITLE
artwork_url & artwork in atvremote

### ISSUE THREAD

**Issue by NebzHB** [postlund/pyatv#156]
Hello, 
artwork_url don't seems to work fine as there is no login session handled before (session_id is 0) so the URL might be useless

about artwork, i don't know how to use the returned data...
if i do : 
```
atvremote --address 192.168.1.66 --login_id [ID] --debug -v artwork > test.png
```
the debug message tells me that : 
```
DEBUG: GET URL: http://192.168.1.66:3689/login?hsgid=[ID]&hasFP=1
DEBUG: _login_request: mlog: [container, dmap.loginresponse]
  mstt: 200 [uint, dmap.status]
  mlid: 8 [uint, dmap.sessionid]

INFO: Logged in and got session id 8
DEBUG: GET URL: http://192.168.1.66:3689/ctrl-int/1/nowplayingartwork?mw=1024&mh=576&session-id=8
DEBUG: _get_request: b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x02X\x00\x00\x02X\x08\x02\x00\x00\x001\x04\x0f\x8b\x00\x00\x00\x01sRGB\x00\xae\xce\x1c\xe9\x00\x00@\x00IDATx\x01\xec\xbdw\x93\xe3F\xd3\xed\tK\xd0\xb6\x1d#\xe9}\x9f{\xe3F\xec\xf7\xff8\xfb\xc7\xc6\xc6\xc6\xbd\x8f\x914\xd3\x8e\xde\xc0\xee\xefT\x91l\xb6\x1b\xf5h\xdap\xba\x13\xa2\xd8 P@e\x1dp\.........
```
which DO seems like a correct PNG header, but in the test.png file i have something like that : 
```
cat test.png
b'89504e470d0a1a0a0000000d49484.......
```
it seems the coding has changed, but i don't see anything into your code modifying that... how would you use it ?

**Comment by postlund** [comment]
Yes, that `artwork_url` is not very useful and will be removed. So avoid using it if you can.

Regarding `atvremote artwork`... The general idea of `atvremote` is to call the API functions and present the result. There are some functions that acts as wrappers (like `pair` for instance) but most just return whatever is returned from the device. What you see is the binary data of the image represented as a python byte sequence, which is correct.

If you want to save the image to a file, use `artwork_save` instead. It will take the binary data and write it to a binary file, i.e. you will get a normal PNG-file. Currently it's not possible to specify output path that way though.

**Comment by NebzHB** [comment]
ok that might solve the problem for me, thanks !

for future idea, maybe artwork should display the artwork in base64 format for web interface use ;-)

i know atvremote is just a POC of the atv class but it's very usefull in domoticz/homeassistant like linux disto, i'm coding a plugin for Jeedom domotic french solution, that's why i ask so many questions ;)

**Comment by postlund** [comment]
It would be quite easy to add like an `--output` flag to specify output file, but I haven't felt that it has much priority.

The problem with doing such a thing (present as base64) is that is requires special handling for one particular function, which is exactly the opposite of what I want `atvremote` to be. It will just make it more complex and harder to maintain. I get what you are after (and atvremote must do enough to be useful to users) but it's a trade-off between usability and maintainability. Since pyatv is a python library first and I'm a developer, I prefer the maintainability aspect. But I am open to improvements if someone can come up with a good one. My time is quite limited right now so pyatv development is moving slow.

Another solution is to just write a small script yourself that uses the library, that way you can present the data any way you like. You could for instance use aiohttp to setup a webserver and map routes to different to functions and return JSON data, so it easily integrates with webservices. For instance `POST /play` causes media to play  or `GET /artwork` returns artwork in some way.
