### ISSUE TITLE
Version 2.2.0 of hass-atv-beta fails to communicate with Apple TV 4K

### ISSUE THREAD

**Issue by villasenor** [postlund/pyatv#1570]
### Describe the bug

Upon upgrading from `v1.8.1` of hass-atv-beta to `v2.2.0`, I'm unable to communicate with my Apple TV. Downgrading to `v2.1.0` solves the problem. The Apple TV is on a separate VLAN, but mDNS relay is enabled, and this has never been a problem before. Additionally, `v2.1.0` works fine!

### Error log

n/a

### How to reproduce the bug?

1. Install `v2.2.0` of hass-atv-beta
1. Successfully complete pairing
1. Note in the Home Assistant UI that OS version, model number, etc isn't populated.
1. Also note that in the Home Assistant UI, no play status information is conveyed, and turn on/turn off no longer works

### What is expected behavior?

After pairing, communication with the Apple TV should proceed as normal.

### Operating System

Linux (Debian)

### Python

3.9

### pyatv

Unknown (whatever hass-atv-beta v2.2.0 uses)

### Device

Apple TV 4K First Gen tvOS 15.1.1

### Additional context

Downgrading to v2.1.0 solves the problem.

**Comment by postlund** [comment]
Hmm, are you sure there's nothing in the log? Otherwise, please enable additional logging.
Hopefully it can help out troubleshooting this.

https://github.com/postlund/hass-atv-beta#debug-logs

**Comment by Eightplant** [comment]
I am in the same boat.  I'll generate some logs tonight.

**Comment by Eightplant** [comment]
Prior setup that worked was ATV's in the user VLAN.  Home Assistant in server VLAN. mDNS on USG 4 Pro turned on.  ATV Airplay and HomeKit setting = Everyone

After update.  With Airplay and HomeKit setting at everyone I cannot connect.  If I change that settings to "Anyone on the same network" I can pair but have no actual control.

I pulled some longs and it appears like the devices are polled successfully by pyatv scan.

What is the best way to get you those logs?  Thank you!

**Comment by postlund** [comment]
Send them by email to me, you have the address in my profile. I'll have a look as soon as I can!

**Comment by villasenor** [comment]
If additional data is needed, I can get around to testing this again, but don't want to break the working system if I can help it :) Thanks for all the hard work you put into maintaining this @postlund!

**Comment by postlund** [comment]
Ok, so, I think I understand now. In the latest change, @bdraco made a bunch of awesome optimizations since my scanning code generated a *lot* of duplicate traffic and high CPU usage. One relevant change is that instead if performing a multicast scan and look for identifiers belonging to the discovered device, a unicast scan toward the device address is performed instead. This is the most logical way of doing things, the problem is however that unicast scanning does not work across VLANs.

So, @bdraco, this became an unintended issue with the change. What would be your recommendation here? I guess it hits both config flow and connect loop.

**Comment by bdraco** [comment]
We probably have enough data in the multicast discovery being fed into the config flow, if we add the device info type.  With *think* we have all the data we need and could skip the unicast probe entirely (probably want to still do it but not treat it as a failure if the multicast data is fresh) and extract the data from the aggregated multicast discoveries going into the config flow.

Long term, I think the best course would be to get everything working with `zeroconf` since it means we only have one listener processing the multicast traffic firehose since it implements the traffic reduction techniques described https://datatracker.ietf.org/doc/html/rfc6762#section-7

**Comment by postlund** [comment]
The problem is that only pyatv can create the config needed to connect, i.e. what you get from `pyatv.scan` and pass to `pyatv.connect`, and there's no way to take externally cached zeroconf information and "convert" it into a config. I guess we in theory could introduce some way to pass a cache to `pyatv.scan` but I'm not sure how to do that with a "clean" interface.

**Comment by bdraco** [comment]
In that case, I would normally say we should revert the changes to discovery, but since Home Assistant doesn't support anything that isn't host networking or mdns repeaters, its hard to justify doing so since it means everyone who has a supported setup has the pay the performance penalty.

**Comment by postlund** [comment]
One idea is to add multicast scanning back to the config flow and accept the small penalty that gives (it should only result in one scan per device and we could probably use the aggregation time to create a cache and share discovered devices if we want?). Then we can add an "aggressive" option that users can enable via Options, in case they have devices on a separate VLAN. Best that I can come up with that doesn't involve a lot of work-arounds.

**Comment by bdraco** [comment]
Here is a proof of concept branch that uses zeroconf for scanning. 

https://github.com/bdraco/home-assistant/tree/scanner_use_zc

**Comment by chrisboulton** [comment]
Still early, but I took @bdraco's changes and have them running locally and seem to have reliable discovery & status detection of Apple TVs and HomePods. Prior to this (similar network setup), I too couldn't get discovery functional on 2.2.0 and reverted to 2.1.0 where I had intermittent discovery and random disconnects. Both seem to be resolved, text to speech works, etc.

**Comment by bdraco** [comment]
Running this for a few hours, everything seems to be working well in my production setup.  Surprisingly its actually using less cpu even though its multicast because most of the queries are in the cache so they don't actually send anything.

**Comment by bdraco** [comment]
I'll wait for feedback on the approach before moving this forward

**Comment by postlund** [comment]
I have only skimmed the changes, but I like the idea of fetching everything from the cache. We are back to the migration to python-zeroconf, which is the proper solution. Maybe we can refactor the scanning into two steps, so the first step only deals with populating the cache and the second one is extracting data from the cache. That way we can obtain the result we are after by setting scan time to 0, which only retrieves whatever is in the cache. Anyhow, changes must be made in pyatv as these changes heavily rely on internal API.

**Comment by bdraco** [comment]
I've done some more cleanup and testing.  I'll open a PR shortly

**Comment by villasenor** [comment]
Thanks so much for all the hard work everyone! Really appreciate it. So the fixes will be in HA 2022.1.X I assume? Also, will there be a new version of the hass atv beta? @postlund

**Comment by Eightplant** [comment]
Thank you!
