### ISSUE TITLE
Showing my three HomePod mini’s

### ISSUE THREAD

**Issue by jackflem1** [postlund/pyatv#1643]
### What do you need help with?

Intergration is showing my HomePod mini’s as available to add as Apple TV.

**Comment by postlund** [comment]
Yes, that is intended behavior. The Apple TV integration supports all devices that pyatv does, including HomePods. Ideally the integration should change name to something else as it targets Apple technologies in general now, rather than just Apple TVs. But that's a hard breaking change, so it will have to do.
