### ISSUE TITLE
How to route traffic through VPN?

### ISSUE THREAD

**Issue by shikata-ga-nai** [postlund/pyatv#1835]
### What do you need help with?

I've setup VPN connection from my laptop to my home router and I want to run atvremote scan through VPN's source IP address/interface. 

The routing table I have is:
```
netstat -rn
Routing tables

Internet:
Destination        Gateway            Flags           Netif Expire
default            192.168.137.1      UGScg             en0       
default            link#21            UCSIg          utun10  
...
192.168.50         10.8.0.1           UGSc           utun10 
```
Apple TV in my home has IP address of 192.168.50.213.
Ping command succeeds against the host, but when I try to point atvremote on the ip address via 
`atvremote --scan-hosts 192.168.50.213 scan `, it just prints empty results
```
Scan Results
========================================
```

Could you please advise if there's a way to point the atvremote through the VPN to the Apple TV?

**Comment by postlund** [comment]
You either have to change so that the VPN assigns IP addresses from the same network as your Apple TV or set up an MDNS responder that relays MDNS packets from your network over VPN. A device is not supposed to respond to MDNS requests from devices on another network, so unicast scanning (`--scan-hosts`) will not work.

**Comment by postlund** [comment]
Really old issue, so I'm closing this now. If you came up with a nice guide, it could possibly be added to the documentation.
