### ISSUE TITLE
Why is this made in Python

### ISSUE THREAD

**Issue by IsakTheHacker** [postlund/pyatv#1992]
### What do you need help with?

First of all, I want to thank you for your enormous efforts in developing and maintaining this library. This is one of, if not the best Python libraries I have come across, good documentation, self-explanatory API and excellent sample programs.

But I have to ask out of curiosity, why is this implemented in Python? Is it because that's what you know best or is there some dependency only available for Python, maybe? For something this advanced and low level I think it would have made sense to write the library code in C/C++ or Rust to make it easier to port/write bindings for other languages.

The interesting thing that I found when I searched for similar libraries is that I didn't find a SINGLE ONE AT ALL. Is your library the only apple tv remote library that is open source, or do you know of any other libraries with similar functionality.

Thank you, again, for maintaining and continuing to support pyatv

**Comment by postlund** [comment]
Hi and thank you 😊

The reason this library is written in python is because it was created for adding Apple TV support in Home Assistant. As Home Assistant is written in python (and require all interaction with external services/devices to be made via an external libraries), python it was. It also aligned pretty well with me wanting to learn more about python. The library is over five years old now, which is nuts.

There's really nothing in there that forces it to be python, could be anything. Tricky pars (that would require libraries) are mainly cryptography, audio decoding (for AirPlay streaming) and possibly network interaction. Python however brings a few benefits at no additional cost, like supporting multiple operating systems.

Initially I relied a lot on other people's work for understanding the protocols involved. As MRP, Companion and lately MRP-over-AirPlay is/was pretty much undocumented I had do to that work myself (which I have documented as well as I could). As I was the first one implementing those protocol, at least publicly and outside of Apple, that's the reason why there are no other alternatives I guess. Unless on one sees a reason to re-implement some functionality in another language then it's not gonna happen. But I have at least tried to make it easier by documenting the protocols (I.e. give back for what I got when I started) 😊

**Comment by IsakTheHacker** [comment]
Hi and thank you so much for your quick response. Seems like there are pretty good reasons as to why this is a Python library. Still surprising to me that no one has open-sourced something similar to pyatv. I have absolutely no problem with Python, it was my first language after all, the only thing that's a bit sad with pyatv is that Python makes it really hard to integrate into embedded devices (which can't run a full-blown Python interpreter)
