### ISSUE TITLE
rpi4: atvremote stream file very slow to HomePods

### ISSUE THREAD

**Issue by aboulfad** [postlund/pyatv#2082]
### What do you need help with?

Hello,

atvremote is slow on an rpi4 where it takes anywhere from 11-13s to complete streaming a 1s audio file. rpi4 & HomePod mini is on same subnet. Full debug Log attached. It seems there's a very large delay (8s) between sending a RTSP SETUP msg and its response. Then another delay ~ 5s that includes streaming the file.

Appreciate any suggestions to further debug this. Thank you !

- rpi4: Bullseye, atvremote v0.13.0
- HomePod mini: 16.5
- `atvremote --debug --verbose -s 10.10.10.10  --scan-protocols raop stop set_volume=50 stream_file="./media/test.mp3"`
[atvremote-slow.log](https://github.com/postlund/pyatv/files/11927225/atvremote-slow.log)

**Comment by aboulfad** [comment]
Any suggestions ? I can reproduce this at will so it’s possible it’s something with my setup. Appreciate any help. I realize that it’d still take some time (3-5s) as each request goes thru establishing a session, encryption, … but 13s or sometimes 15s is very slow.

**Comment by postlund** [comment]
Sorry about the delay! Yes, the HomePod takes a painfully long time before it responds to SETUP for some reason. This started a while back, it hasn't always been that way. I haven't managed to figure out why yet, but if I do I will of course fix it. As AirPlay uses a buffer time of about two seconds, total time should be play time + 2 + overhead to load pyatv + connect time and all that. 13-15s is way too long IMHO, but I don't have any solution right now (feel free to poke around if you like).

**Comment by aboulfad** [comment]
Thanks, appreciate the input. I wonder if either HP mini is notorious for this and/or 16.5. If there’s other debug  stuff to try, plz lmk. I’ve exhausted all different ways to stream audio, manual, unicast, …

That’s unfortunate as pyatv is the only means to use the HomePods as speakerphone for home automation without additional subscriptions. Thanks again.

**Comment by jreed509** [comment]
I'm also seeing a long delay on my (original) HomePods. This does appear to be specific to HomePods though since other airplay compatible devices I have seem to play tts messages much quicker. 

One other interesting bit of behavior I've noticed is that the delay appears to be significantly shorter for additional streams back to back. For example the first time I play a stream the delay might be ~15 seconds, but if I try to play another stream again not long after the first one finishes, the delay is only ~4-5 seconds. Playing media from other sources in between (say from Apple Music on the HomePod) results in that long delay again.

**Comment by aboulfad** [comment]
That's very intriguing & disapointing. I have 3 HomePod minis (different yearly models) and they all 3 have this long delay. When used in home automation, it will be one message at a time so that long delay will always be incurred.

**Comment by postlund** [comment]
The long delays seemed to happen only for HomePods for some reason. It started a few releases back because that has not always been the case. My hopes is that it fixes itself in an upcoming release, but I will keep experimenting myself in the meanwhile.

I can't really see any issues in the feature flags, but I'm gonna try to create a branch using ALAC instead and see if that helps. Would be great if someone could reproduce this with atvremote instead from `main` in the path repo.

**Comment by aboulfad** [comment]
Hi,

I did search in the issues but couldn’t find a related report, sorry if I missed it. Next HomePod (HP) release is 17.0 in Sep/Oct so yeah let’s hope it’s fixed. Do you recall roughly which HP release the delay was reasonable ? 

Are you asking once you create a branch with ALAC, to grab that branch and use atvremote to reproduce the issue? It could be helpful to have some quick way (flag or otherwise) to switch between LPCM & ALAC if you are suspecting this, thank you.

**Comment by postlund** [comment]
I don't recall the version exactly, no. But it's the current major release at least.

Yes, exactly. I've would create a new branch using ALAC instead. I've stripped all that code, so I would have to revert that. In that case, only ALAC would be used so using that branch would be the only requirement. But I can add an environment flag to toggle simply as well.

**Comment by jreed509** [comment]
@postlund I noticed you created an ALAC branch in https://github.com/home-assistant/core/issues/95993 so I figured I'd give it a quick try on my homepods to see if it improved response times. 

Using the following command, I didn't see any noticeable improvement in response time vs on main:
```
atvremote -s <ip to my homepod> stream_file=./test.mp3
```

Additionally, when using this branch the audio was extremely distorted. I imagine this is just a bug during encoding the file as ALAC and unrelated to this particular issue, but figured I'd point it out.

**Comment by postlund** [comment]
@jreed509 Main reason for that branch is testing with a Belkin device where audio doesn't work, but it's interesting that the audio is distorted. It shouldn't be.  Scratch that (edit as I'm writing this). Samples are endian-swapped twice, so that would explain in. I will push another update, thanks for pointing that out as I didn't have any possibility to test my changes due to traveling.

Using ALAC adds more overhead, so it should be "a lot" worse than using PCM. Biggest issue here is the time for SETUP.

**Comment by postlund** [comment]
@jreed509 Just pushed an update with fixed endianness, can you verify if audio is still distorted?

**Comment by jreed509** [comment]
Makes sense, thanks! You mentioned using ALAC as a possible fix to this issue as well so I figured I'd give it a go.

> I can't really see any issues in the feature flags, but I'm gonna try to create a branch using ALAC instead and see if that helps. Would be great if someone could reproduce this with atvremote instead from `main` in the path repo.

Let me know if there's anything else to test for this issue (although it sounds like this might just be an issue on apple's side and we may just have to wait till homepod os17 and hope things are faster)

**Comment by jreed509** [comment]
> @jreed509 Just pushed an update with fixed endianness, can you verify if audio is still distorted?

@postlund Yep confirmed ALAC audio sounds correct with that latest commit

**Comment by CAB426** [comment]
FWIW, I updated my HomePods to iOS 17 Public Beta and my delay playing TTS WAV's (local) went from ~10s to ~3s.  This is through Home Assistant (2023.7.2), local Piper TTS (Latest - <1s response time), and HomePod Gen 2.  I ensured that they were not cached and also tried after 60 minutes to let everything "cooldown", same results.

**Comment by aboulfad** [comment]
> FWIW, I updated my HomePods to iOS 17 Public Beta and my delay playing TTS WAV's (local) went from ~10s to ~3s. ...
That sounds very promising, thanks for trying. I hope that it will be the same for HomePod Minis too.

**Comment by postlund** [comment]
@CAB426 Thanks got reporting! That is very  reasonable. AirPlay has some buffering time built in which is about two seconds, so that sounds about right. Since this penalty delay was not present before, I kinda suspected that apple messed up. They do that from time to time.

@aboulfad It will be, is the same software.

**Comment by aboulfad** [comment]
Indeed, I can confirm much shorter acceptable delay ( ~4s) with HomePod beta 17 on one of my HP Mini, streamed with the same command as my OP (from rpi4) :)

**Comment by ultimate-tester** [comment]
I know last activity here was 4 months ago, but wanted to share that the release notes of the HomePod update says/

`Software version 17.1.1 addresses an issue where some HomePod speakers could respond slowly or fail to complete requests`

I think the ticket can be closed. Also, it was never limited to raspberry pi as the title suggests.

**Comment by aboulfad** [comment]
Seems to be fixed in 17.x
