### ISSUE TITLE
KeyError: '4' setting up Apple TV

### ISSUE THREAD

**Issue by jcollas** [postlund/pyatv#281]
**Describe the bug**

Getting this exception when entering the pin in the configuration flow.  Happens every time.

2019-11-25 19:42:13 ERROR (MainThread) [custom_components.apple_tv.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 175, in async_step_pair_with_pin
    await self._pairing.finish()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/pairing.py", line 45, in finish
    await self.pairing_procedure.finish_pairing(self.pin_code)
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/auth.py", line 64, in finish_pairing
    atv_proof = pairing_data[tlv8.TLV_PROOF]
KeyError: '4'

**To Reproduce**

Add the integration for the Apple TV, and enter the PIN shown on the Apple TV.

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: [e.g. Debian]: Raspbian 4.19.75-v7+ #1270 SMP
 - Python: [e.g. 3.6.2] 3.7.3
 - pyatv: [e.g. 0.3.10] pyatv-0.4.0a4

**Additional context**

Here's the log file:

[pyatv.log](https://github.com/postlund/pyatv/files/3891811/pyatv.log)

**Comment by postlund** [comment]
Hmm, this is strange. First of all, the snippet you posted above is not from the attached log (timstamp differs). So this must be from two different points in time, seems to be about 10min apart. In the log, `pyatv` seems to connect and set everything up as expected (but I see that I have to make some adjustments to the connection flow, but that's for later). So the pairing must have succeeded at some point, otherwise there would be no credentials. There wouldn't even be any entities in Home Assistant as no config entry will be created before pairing has succeeded for both MRP/DMAP and AirPlay. So I have a hard time seeing that it fails *every* time?

Can you elaborate on exactly what you are doing? Would be good if you removed the Apple TV from the Integrations page and restart Home Assistant. You could even bump to the latest update of the component, using `pyatv` 0.4.0a5 that I pushed earlier this morning.

**Comment by jcollas** [comment]
Just tried it with your latest Apple TV integration release (4944a51), and pyatv 0.4.0a5.  Got a different error.

[pyatv-2.log](https://github.com/postlund/pyatv/files/3892088/pyatv-2.log)

**Comment by postlund** [comment]
Great, that seemed to do the trick. Now it's the same problem as in #279, a fix will be available soon.

**Comment by postlund** [comment]
New update is pushed, please update component and try again!

**Comment by postlund** [comment]
@jcollas Can you verify if you still see this issue and close it if you don't?

**Comment by jcollas** [comment]
This bug is fixed.  I’ll close the issue when I get to a real computer

**Comment by postlund** [comment]
Awesome! 👍
