### ISSUE TITLE
Command for player skip forward/back 10 seconds

### ISSUE THREAD

**Issue by tal** [postlund/pyatv#345]
Is there a command for telling the active player to skip forward/back? This shows up on the iPhone remote or on the built in remote if you click on the edges.

**Comment by postlund** [comment]
It is possible, of course, but not implemented in `pyatv` yet. You have the various commands here:

https://github.com/postlund/pyatv/blob/master/pyatv/mrp/protobuf/CommandInfo.proto

Adding support for it should be quite simple. The trickiest part is defining a good API to avoid having a billion methods in the remote control interface. If you feel like implementing it, give it a spin. Otherwise I can add it as a feature request for the release after 0.4.0.

**Comment by tal** [comment]
It looks like there’s a small finite number of commands. Why are you concerned about too many methods in the control interface?
  

  
  

  
  
>

**Comment by postlund** [comment]
There's a finite amount of commands, yes, but I don't want to end up with various strange combinations that might or might not be consistent. The `home` and `home_hold` methods that are currently in the remote control interface is an example of that. It's the same button, but it would make more sense to have a hold-flag. Maybe also a duration, in case that's important. I intend to change that particular case soon just because it makes more sense. But I need to come up with a strategy to make it consistent and I haven't bothered looking into it yet. It also needs to fit with #268 later on. Minor things.

**Comment by postlund** [comment]
Working on this now, will probably finish it off tomorrow or so if things go as expected.
