### ISSUE TITLE
See what app is running in Home Assistant

### ISSUE THREAD

**Issue by robbinonline** [postlund/pyatv#376]
Pyatv is great to get a AppleTV working again on Home Assistant with iOS 13.
Is there a possibility to get the status what app is running on the AppleTV?

Now its only shows the stream information:
`media_content_type: video
media_position: 38
media_position_updated_at: 2020-01-15T09:55:51.099571+00:00
media_title: No title
friendly_name: AppleTVwoonkamer
entity_picture: /api/media_player_proxy/media_player.woonkamer?token=66e20009e691de0fec9444a17814bf370c4b4d4c71b75a591e0251f60fe34408&cache=d5c4d2ebc764345f4f62e3771c29189ea66e844ba6871968607858027e4c4fb0
supported_features: 21427`

I would be nice to see what app is used for playing like YouTube or Plex.
Then it would be usefully for a automation by Example when Plex is playing dimm lights.

**Comment by postlund** [comment]
It will be supported later, but it is not a priority right now and not trivial to implement as I haven't investigated everything yet. Please see #302 for details.

**Comment by postlund** [comment]
Support for playing app was added in #498, so it will just have to be implemented in Home Assistant in due time. Just need to find some time to finish the component PR.

**Comment by robbinonline** [comment]
Looking forward to it!

**Comment by Neejoh** [comment]
Really excited about this. I can't wait to be able to use the app name in automations in Home Assistant!

Since [hass-atv-beta](https://github.com/postlund/hass-atv-beta) implements [pyatv](https://github.com/postlund/pyatv/), will this require a lot of work or will it be worked on relatively soon-ish? It will have high WAF!

**Comment by postlund** [comment]
@Neejoh It is super-easy to add (especially since I maintain both projects) and I have in fact already added it. I plan to release an update next week. There's unfortunately small bug in there that makes the app name unavailable. For some reason the device doesn't always send it. So I will have to make a workaround for that. The app identifier (e.g. com.netflix.Netflix) is however always present, so it's possible to uniquely identify apps.

**Comment by Neejoh** [comment]
That’s awesome man, much sooner than I expected. Thanks for
Keeping this train rolling.

**Comment by postlund** [comment]
@robbinonline  @Neejoh A new release of the component is out now with support for running app. Feel free to upgrade and try it out (read the note in readme though).

**Comment by Neejoh** [comment]
@postlund Gave it the first test drive and so far, so good! Super happy with it.

**Comment by Neejoh** [comment]
Still going strong, have not run into anything yet.

The one thing I'm missing (and is probably just not possible, but you never know until you ask) is to know what app is open while idle and not just when playing. Is that just a limitation or is a feature request in place here?

**Comment by postlund** [comment]
It's a limitation in the protocol (i.e. not possible) I'm afraid.

**Comment by postlund** [comment]
I'm going through some old issues and I find this to be solved. Please do write a new issue if you have any problems.
