### ISSUE TITLE
Connecting triggers devices to turn on

### ISSUE THREAD

**Issue by philk** [postlund/pyatv#39]
First, thanks for this and the home-assistant integration, it's awesome.

The issue I have is on restart of home-assistant it triggers the TV (in my case a projector) to come on. In case it was just a home-assistant issue I tested with the `auto_connect.py` example which causes the same thing.

This is a pretty big caveat since at least in my case turning on the ATV triggers some other automation and I don't want to sacrifice being able to having everything come on by just hitting the ATV remote.

Is there a way in the protocol to detect if the ATV is in sleep?

**Comment by postlund** [comment]
Hi and thanks for the feedback! :)

This is an issue, I agree. I haven't found any way to determine that I'm afraid. But it seems to be a standing issue as I've heard others with basically the same behavior. A question regarding your setup. Is it that your projector wakes up because the HDMI-output on the Apple TV is activated?

**Comment by robbiet480** [comment]
The projector is waking up because Apple TV is waking up and sending a Power On command to all HDMI connected devices via CEC.

**Comment by philk** [comment]
Yup, that's it. You can turn off that functionality but it's nice to have
our happen when you hit the remote.

**Comment by postlund** [comment]
Ok, I _think_ I know how to do this :) Bear with me... The device goes to sleep and registers itself to a Bonjour Sleep Proxy, like a computer or AirPort express. You can see if you have one with:
```
Linux: avahi-browse _sleep-proxy._udp
macOS: dns-sd -B _sleep-proxy._udp local
```
The Bonjour Sleep Proxy will take responsibility of the device (Apple TV) and answer to ARP requests. So, if you have an Airport Express that acts as a proxy, it will broadcast that the IP-adress of the Apple TV with the MAC-address of itself (ARP). When someone tries to access (e.g. ping) that IP-address, the request will end up at the Airport Express which in turn will wake up the Apple TV with a magic packet. After this the Apple TV takes over its IP-address again as usual.

What I'm thinking is that if we know the MAC-address of the Apple TV in question, we can just compare that with current value in the ARP table and be pretty sure if it's asleep or not. Then we can act based on that. Maybe we can add a new API to check if the device is asleep or not (pyav.is_apple_tv_in_standby?). If we currently don't have that MAC-address in the ARP-table, we just make an ARP-request and wait for the response (an ARP-request will not wake the device). Pretty cool I must say, but it will only work if there is a device acting as proxy on the network.

Good reference: http://www.cnpbagwell.com/mac-os-x/bonjour-sleep-proxy

**Comment by postlund** [comment]
My theory above did not bear any fruit, it was too unreliable. I implemented a work-around a while back in Home Assistant, see this PR: https://github.com/home-assistant/home-assistant/pull/5962. It is probably as good as it's gonna get for now. In order to still use the Apple TV, I would suggest that you write an automation that turns it on/off depending on some other condition, like if a certain source is selected on your receiver. That is probably the best way to do it, as long as CEC is enabled.

**Comment by Nedryland** [comment]
This is an old post but wanted to leave my experience in case someone else stumbles across this and has similar issues. My apple tv wasn't powering on randomly but just the same I wanted to be able to monitor the on/sleep status. I set up a ping sensors for two apple tv 3s successfully, however when I put atv1 to sleep, atv2 started to return a ping. After reading about bonjour sleep proxies I determined that atv2 had registered with atv1 spleep proxy, so once that proxy went to sleep it reverted to it's own mac address and answered pings directly. To fix the issue I unplugged both atvs, then powered on atv1 and put it to sleep, then I powered on atv2 and put it to sleep as well. This forced each to register with my time capsule/airport extreme and now the ping sensors work properly once again. 

I woke and slept them again several times in random orders and all seems well for now. Luckily I have a time capsule as I'm pretty certain that this would not work without it. I also could not find a way to force an atv to use a specific sleep proxy without powering things on in specific order, however they should default to the time capsule if available. My theory is that one atv registered to the other when at some point I rearranged some patch cables and the time capsule wasn't available temporarily.

Another less accurate (and messy) method is to (1)create an input_boolean for the power status (2) an automation that turns on the input_boolean whenever the media_player state goes from idle to playing or when ever you send a remote command (3) an automation that puts the apple tv to sleep manually by calling remote_send commands and also turns off the input_boolean. In order for this to work with any accuracy you have to disable the auto sleep function in the apple tv and always call sleep function from HA, as HA will have no way of knowing if the atv puts itself to sleep. 

I used this method for awhile until I decided to finally figure out the ping issue and it works reasonably well as long as you get your sleep automation or script working reliably (you have to get the timing right and put delays between remote_send commands because if you issue to many too fast it will skip some). I have one automation that navigates to the same spot on the home screen no matter where I happen to be. I call this first from other navigation automations such as sleep which then goes five spaces to the left, into "settings" and down to "sleep now". I also have single button shortcuts (automations) for HBO, Netflix, Plex, etc. which I can then call from siri (very handy).

**Comment by Nedryland** [comment]
This is an old post but wanted to leave my experience in case someone else has similar issues. My apple tv wasn't powering on randomly but just the same I wanted to be able to monitor the on/sleep status. I set up ping sensors for two apple tv 3s successfully, however when I put atv1 to sleep, atv2 started to return a ping. After reading about bonjour sleep proxies I determined that atv2 had registered with atv1 spleep proxy, so once that proxy went to sleep it reverted to it's own mac address and answered pings directly. To fix the issue I unplugged both atvs, then powered on atv1 and put it to sleep, then I powered on atv2 and put it to sleep as well. This forced each to register with my time capsule/airport extreme and now the ping sensors work properly once again. I woke and slept them again several times in random orders and all seems well for now. Luckily I have a time capsule as I'm pretty certain that this would not work without it. I also could not find a way to force an atv to use a specific sleep proxy without powering things on in specific order, however they should default to the time capsule if available. My theory is that one atv registered to the other when at some point I rearranged some patch cables and the time capsule wasn't available temporarily.

Another less accurate (and more complex) method is to (!)create an input_boolean for the power status (2) a template sensor that that echoes "off" if media player state is idle and echoes "on" if media player state is anything else (the values "on" "off" can be anything.. you just need two different states as the media player state .

**Comment by Nedryland** [comment]
As a follow up to the previous post.. After awhile I noticed that the apple tv ping sensors were returning randomly every 10-15 minutes or so when set at 60 second intervals, and every 5-7 minutes or so when set at 25 second intervals. This tells me that it's likely related to the number of pings and not the amount of time that has passed. I tried using an arp command to reference the mac address and same story. The arp command sensor behaved the exact same way. So for some reason after x amount of queries the sleep proxy allows a direct response?

So how did I solve the problem of an occasional false return? 

(1) A ping or arp sensor running every 25 seconds and echoing 'on' or 'off'. 

(2) An automation triggered by the ping going from 'off' to 'on'; 60 second delay;  "homeassistant.turn_on" "input_boolean.yourboolean1"; 2 second delay; "homeassistant.turn_off" "input_boolean.yourboolean1" 

(3) Another automation triggered by "input_boolean.yourboolean1"; with condition that the ping sensor is 'on'; then "homeassistant.turn_on" "input_boolean.yourboolean2"

(4) Use "input_boolean.yourboolean2" as your sensor or reference it in a binary or template sensor

In this way by the time the second automation kicks in, the ping sensor has already ran 1-2 more times ensuring that it will be back to 'off' state, therefore the condition will not be met and the second input_boolean (the one we are using for our sensor) will remain off. When the apple tv is actually on it will return all pings, the condition is met, and the second input_boolean is turned on. This has so far worked like a charm.

I also tackled the sleep and display status of my MacBook, which of course have their own idiosyncrasies involving a sleep proxy and what not. I tried everything I could think of. When the mac is asleep with wake for network access enabled and you send an ssh command from HA it will wake the mac and unlike the atvs it always returns a ping. So sending commands of any kind for status while sleeping is pretty much not an option.

What did I come up with in the end?

(1) 2 command_line sensors that read txt files on a network share. One for sleep status "power.txt" and one for display sleep status

(2) A script that runs on the MacBook "displaystatus.sh" and writes the display status to the "display.txt" file every 30 seconds

(3) Sleepwatcher2.2 running on mac that runs a script before sleeping and after waking up. The sleep script stops "displaystatus.sh" and writes 'off' to both "display.txt" and "power.txt". The wake script writes 'on' to "power.txt" and starts "displaystatus.sh"

I configured the display status with the additional script because I couldn't get Sleepwatcher to work with the display status, but it is supposed to. I could only get sleep/wake and plug/unplug triggers to work for now. Sleepwatcher also does not seem to be triggered by login or logout, shutdown or reboot so may need additional script to run a boot to get things started. I have not gotten that far as I very rarely power down or restart. It's not perfect but It's accurate and works fine for now.

Hopefully someone struggling with apple integration can find all this useful. This issue drove me crazy until I came up with something reliable enough that I could trigger automations.
