### ISSUE TITLE
play_media does not work

### ISSUE THREAD

**Issue by TheCellMC** [postlund/pyatv#444]
First all, thanks for the amazing work your are doing at supporting the new standards which Apple brought through tvOS 13.
I have been able to successively set up this component to control my tv and see what is currently playing through Home Assistant.
Unfortunately, I am unable to get the play_media service to work. I am running the latest version of your custom component.

I am able however to manually play my content using the atvremote command installed on my mac using the same credentials generated by hass. So I am able to get it to work using this command on my Mac:` atvremote --id RE:DA:CT:ED:00:00 --airplay-credentials REDACTED play_url=https://domain.com/local/videos/test.mp4`. However even this command does not seem to run reliable as sometimes I get the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 565, in _run_application
    return await cli_handler(loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 388, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 480, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 517, in _handle_device_command
    return (await _exec_command(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/__main__.py", line 531, in _exec_command
    value = await tmp(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/airplay/__init__.py", line 71, in play_url
    player = await self._player(session)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/airplay/__init__.py", line 51, in _player
    await verifier.verify_authed()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/airplay/auth.py", line 88, in verify_authed
    resp = await self._send(self.srp.verify1(), 'verify1')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/airplay/auth.py", line 100, in _send
    resp, code = await self.http.post_data(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/net.py", line 76, in post_data
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyatv/net.py", line 64, in post_data
    resp = await self._session.post(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

Here is what I tried in the hass dev tools:
```
entity_id: media_player.apple_tv
media_content_id: 'https://domain.com/local/videos/test.mp4'
media_content_type: video

```

**Comment by postlund** [comment]
Thank you for trying it out 👍 

AirPlay does have some funky things going, not sure why. But it doesn't always respond in the way that I would wish for. Based on the logs here though, it's authentication that times out. That is actually new to me. I'll see if I can reproduce it myself at home.

Would appreciate if you stick to the bug issue template for future issues (just a kind reminder) 👍

**Comment by postlund** [comment]
Also, do you get any errors in the Home Assistant log?

**Comment by TheCellMC** [comment]
Sorry for not sticking to the template, I do not know why but it did not popup when I created the issue, although it does now. I mussed have clearly missed something.

Weirdly enough, I am not getting any errors in the Home Assistant log.

I also tried rolling back to an older version of the component, and it turns out that this issue is no longer present when using version 0.4.0a12.

**Comment by postlund** [comment]
No worries 😄 

Do you see anything in the Home Assistant log at all when starting to play? You need to enable debug logs before you get anything interesting I guess:
```yaml
logger:
  logs:
    pyatv: debug
    custom_components.apple_tv: debug
```

I have not yet been able to reproduce this myself. Not sure why it would happen just some times either, seems weird.

**Comment by postlund** [comment]
Quick note is that I have managed to play http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 without any problems.

**Comment by postlund** [comment]
My main focus is to get PR ready for Home Assistant, should happen today. Will dig deeper into this after that, mainly compare master with a12 release to see if I can find anything that could be the root cause.

**Comment by postlund** [comment]
Oh, oh, I'm starting to see a pattern here. I believe the timeout is because of the device going to sleep (via sleep proxy). I have been babbling on about this in #580, so I'm gonna spare the details. But the behavior definitely correlates. The device will automatically wake up when you try to connect to it, but it can take some time. My non-scientific tests on an Apple TV 3 points towards 20 seconds or so (give or take). The timeout for requests in `pyatv` is 10 seconds, so the they will likely fail. Making another try will likely succeed however.

The wake up time is something I can't do anything about, it is how it is. I can (and will) add mitigations to automatically wake up the device when needed and in some places adjust time outs accordingly. The only way to mitigate this completely is to disable auto-sleep. If the device is manually put to sleep, this will still be an issue however.

So I guess disabling auto-sleep is the only proper solution here. The mitigations I'm planning might work to some extent as well but you will get long latency when playing something when the device is sleeping. I will look into using `play_url` in Home Assistant, I haven't tried it in a while so perhaps something is broken. I would assume using Home Assistant and keeping the connection active at all time should mitigate this as well.

**Comment by postlund** [comment]
Issue created for it: #595.

**Comment by postlund** [comment]
@TheCellMC  Mitigations for the time out issues should be in place now. If you have some time over, it would be great if you could try out `master` a bit and see if it works more reliably now. Since I closed #95, it's possible to stream local files directly as well. Just specify file name like so:

```
$ atvremote --airplay-credentials <creds> --id <id> play_url=myfile.mp4
```

It will set up a (temporary) web server, serving just that single file and stream from it. A random port is used, so it won't play nice with firewalls for now.

**Comment by TheCellMC** [comment]
Thanks for the amazing work on this @postlund. I have been testing the latest release for the last week and it is working perfectly. The play_media service worked every single time! I am going to close this issue as it appears to be fixed for me.

**Comment by postlund** [comment]
Awesome, thanks for trying it and reporting back! 👍
