### ISSUE TITLE
Interface for device_information

### ISSUE THREAD

**Issue by stickpin** [postlund/pyatv#454]
Hi @postlund,

Following our conversation in HASS integration thread... 

**What feature would you like?**
In case to be able to implement "close to real" Apple TV active/standby status by using device_information.logicalDeviceCount, can you please create/expose an interface for the device_information?

I am new to python, so I don't want to mess too much with your code.

Thanks a lot in advance!

**Comment by postlund** [comment]
Sure, I can help you out with that. You are free to mess around with the code, I can give you some pointers in the PR 😄

The DeviceInfoMessage is an internal message and there's no need to expose it to the public, so we can handle this in any way we like. There's no natural place for it today, but I would suggest to catch it in "protocol" logic, i.e. `pyatv/mrp/protocol.py`. The response from the Apple TV is currently discarded, so we would have to save it as a start. That can be done here (`self.device_info = ...`):

https://github.com/postlund/pyatv/blob/095bcd915aa9bc7ef45542e196080782eca6f19c/pyatv/mrp/protocol.py#L68

I'm not sure how well acquainted you are with MRP, but messages can either be one-shot (send and don't bother about the response), event message (the other device informs about something) or request where a response is expected. Since MRP is asynchronous, requests that expect a response will be assigned a random identifier (UUID4) which is then included in the response. This is done under the hood by the `send_and_receive` method, thus it will "block" until the expected response is received.

The code above will only catch the initial DeviceInfoMessage that is exchanged during connection setup. To get sporadic message, you will have to add a listener. An example of how that is done can for instance be seen here:

https://github.com/postlund/pyatv/blob/095bcd915aa9bc7ef45542e196080782eca6f19c/pyatv/mrp/player_state.py#L100

Some pseudo-code would look like this:

```python
# This should go somewhere
self.add_listener(self._handle_device_info, protobuf.DEVICE_INFO_MESSAGE)

# Implementation of _handle_device_info:
sync def _handle_set_state(self, message, _):
    self.device_info = message.inner()
```

In general, `message` is the envelope message (ProtocolMessage). I have added a convenience method called `inner()` that returns the actual message it represents, e.g. DeviceInfoMessage. So to get logicalDeviceCount, you would do `message.inner().logicalDeviceCount`. I would suggest to store the entire message even though we only use one member now.

Next part would be the external API. I guess we can either add `turn_on` and `turn_off` to the `RemoteControl` interface. Another suggestion is to add a `Power` interface in case we see any benefit of that. Doesn't really matter to me.

Lastly, I understand that it's not easy to get going on something like this in someone else's code base. But feel free to ask as many questions as you need, I will try to answer as good as I can and give pointers 😄

**Comment by stickpin** [comment]
Thanks a lot for the quick reply!

Let me try to explain what I did in Homebridge Plugin.

I was not able to find an elegant way to catch the DEVICE_INFO_MESSAGE during the status change. It seems that ATV not sending DEVICE_INFO_MESSAGE when you suspending or turn on the ATV so I don't think the listener will help here.
The only way I've managed to make it work in kind of near-real-time status update is to run a loop with 5 seconds sleep to send a DEVICE_INFO_MESSAGE and to check logicalDeviceCount in the response.

```
AppleTVAccessory.prototype.checkATVStatus = function () {
    var that = this;

    that.device.sendIntroduction().then(function (deviceInfo) {
            var currentPowerState = deviceInfo.payload.logicalDeviceCount;

            if (currentPowerState >= 1) {
                that.updatePowerState(true);
            } else {
                that.updatePowerState(false);
            }
        })
        .catch(function (error) {
            that.log("ERROR: " + error.message);
            that.log("ERROR Code: " + error.code);
            setTimeout(function () {
                that.log("Trying to reconnect to AppleTV: " + that.name);
                that.atvConnect();
            }, that.retryRate);
        });
}
```

So I think there's no way around and device_info needs to be exposed one way or another.
For example, as it done in node-appletv:
```
    sendIntroduction() {
        let body = {
            uniqueIdentifier: this.pairingId,
            name: 'node-appletv',
            localizedModelName: 'iPhone',
            systemBuildVersion: '14G60',
            applicationBundleIdentifier: 'com.apple.TVRemote',
            applicationBundleVersion: '320.18',
            protocolVersion: 1,
            allowsPairing: true,
            lastSupportedMessageType: 45,
            supportsSystemPairing: true,
        };
        return this.sendMessage('DeviceInfoMessage', 'DeviceInfoMessage', body, true);
    }
```

Please let me know what you think about it.

**Comment by postlund** [comment]
Hmm, that seems like a pickle. When you say "suspend" or "turn on", what exact action are you taking then? I know that I have seen this message in those situations, I did an "extensive" investigation of this a while back. It is here: https://github.com/postlund/pyatv/issues/323

But, ah, now I see it. Initially it sends DeviceInfoMessage, but all updates after that are DeviceInfo**Update**Message. It's the same message but a different id:

https://github.com/postlund/pyatv/blob/095bcd915aa9bc7ef45542e196080782eca6f19c/pyatv/mrp/protobuf/ProtocolMessage.proto#L40

So that is what we should look for. Maybe you can verify if that works for you? Polling like that is not something I would accept as a solution I'm afraid, but I don't think its necessary either.

**Comment by stickpin** [comment]
Yes, you are right!

Turn Off Update Message:
```
2020-02-19 23:49:14 DEBUG (MainThread) [pyatv.mrp.connection] << Receive: Protobuf: type: DEVICE_INFO_UPDATE_MESSAGE
priority: 0
[deviceInfoMessage] {
  uniqueIdentifier: "---"
  name: "Apple TV"
  localizedModelName: "Apple\302\240TV"
  systemBuildVersion: "17K795"
  applicationBundleIdentifier: "com.apple.mediaremoted"
  protocolVersion: 1
  lastSupportedMessageType: 77
  supportsSystemPairing: true
  allowsPairing: true
  systemMediaApplication: "com.apple.TVMusic"
  supportsACL: true
  supportsSharedQueue: true
  supportsExtendedMotion: true
  bluetoothAddress: "---"
  sharedQueueVersion: 2
  deviceUID: "---"
  managedConfigDeviceID: "---"
  deviceClass: 4
  logicalDeviceCount: 0
  isProxyGroupPlayer: false
  groupUID: "---"
  isGroupLeader: true
  isAirplayActive: false
  systemPodcastApplication: "com.apple.podcasts"
  enderDefaultGroupUID: "---"
  airplayReceivers: "TVAirPlay"
}
```

Turn On Update Message:
```
2020-02-19 23:51:44 DEBUG (MainThread) [pyatv.mrp.connection] << Receive: Protobuf: type: DEVICE_INFO_UPDATE_MESSAGE
priority: 0
[deviceInfoMessage] {
  uniqueIdentifier: "---"
  name: "Apple TV"
  localizedModelName: "Apple\302\240TV"
  systemBuildVersion: "17K795"
  applicationBundleIdentifier: "com.apple.mediaremoted"
  protocolVersion: 1
  lastSupportedMessageType: 77
  supportsSystemPairing: true
  allowsPairing: true
  systemMediaApplication: "com.apple.TVMusic"
  supportsACL: true
  supportsSharedQueue: true
  supportsExtendedMotion: true
  bluetoothAddress: "---"
  sharedQueueVersion: 2
  deviceUID: "---"
  managedConfigDeviceID: "---"
  deviceClass: 4
  logicalDeviceCount: 1
  isProxyGroupPlayer: false
  groupUID: "---"
  isGroupLeader: true
  isAirplayActive: false
  systemPodcastApplication: "com.apple.podcasts"
  enderDefaultGroupUID: "---"
  airplayReceivers: "TVAirPlay"
}
```

Nice one! So then the listener can work like a charm here.

Now I don't understand why you still don't have it in pyatv? :) I do agree that there are some edge cases with solution based on HDMI detection, but I think will cover most of the cases and it's for sure better than nothing.

**Comment by postlund** [comment]
Great, then we know what's going on 😄 There are probably a few reasons for it not being in place, but lets just conclude that it should be a good enough solution for being included. We can look at the edge-cases later and call it an "incubating" feature for a while 😉

Do you still want to take lead on adding support for it (with support from me of course)?

**Comment by stickpin** [comment]
@postlund I will try to implement it today.
Let see how it goes. :)

I will keep posted.

**Comment by postlund** [comment]
@stickpin Sounds good 😊 A tricky part will probably be the tests until you get around how they work.

**Comment by stickpin** [comment]
@postlund just to keep you posted.
It was a bit busy week at work. So I've just started to implement the listener for DEVICE_INFO_UPDATE_MESSAGE. 

Going well so far. I will keep you posted on the progress. :)

**Comment by stickpin** [comment]
@postlund please let me know what you think.
I'm introducing a new variable as part of the PlayerStateManager init object.

`self.powerState = None`

and then a DEVICE_INFO_UPDATE_MESSAGE listener logic goes like this:

```
    async def _handle_device_info_message(self, message, _):
        logicalDeviceCount = message.inner().logicalDeviceCount
        if logicalDeviceCount >= 1:
            self.powerState = 1
        else:
            self.powerState = 0
```

I will also need to add a listener for DEVICE_INFO_MESSAGE to make sure that powerState is updated in all the cases.

**Comment by stickpin** [comment]
@postlund here we go... :)
Initial MRP power state support: https://github.com/postlund/pyatv/pull/458

Now working on hass-atv-beta plugin. It should be reasonably simple to implement power state into the plugin and also a real on/off switch. 

To be completely honest the only functionality I need for HASS is On/Off switch with a "real" power state. So maybe it will be better to create a separate plugin only for this purpose and people will be able to get it though HACS.

**Comment by postlund** [comment]
@stickpin Sorry for answering so late as well, been a busy week here too 😄 I've been thinking a bit more about it and what would be the most natural way of implementing the public API. The way I would like to have is `device_state` (in the Metadata interface) to report "standby" or something similar when the device is "off". This seems to not be possible though.

We cannot use `logicalDeviceCount` as it does not always tell the truth. When I push an AirPlay stream to the device when it is "off", the stream will play but `logicalDeviceCount` remain 0 since HDMI is not active. So it's playing but does not have any video output. If CEC is used, maybe the device (and all peripherals) is really "turned on" in this case however? Not really sure. It's hard to reason what is on and off in all situations. I guess that's where I got stuck last time. Also, if the entity reports "standby" as state no controls are available (it is treated as off mor or less). So something could be playing but it would not be reflected nor controllable.

It would be beneficial if power on/off were implemented officially as well, since this is the most requested feature. So I am still keen on finding a solution, but it must be reliable and have a decent API (thinking about ATV3 and earlier is also important). We can always add an option in Home Assistant so that people can opt-in for this feature, in case it doesn't work as expected.

I'm leaning more and more towards adding a `Power` interface that can have a state and `on`/`off` methods. It would encapsulate the power management code in a good way. Since I don't have a solution for pre-MRP devices, #268 would be a prerequisite to revert back to "old" behavior in this case.

**Comment by stickpin** [comment]
@postlund, totally agree with you, it's not possible to cover all the cases especially with old devices.
In my case, I am only using ATV 4 and 4K with TVs connected over HDMI, so for me logicalDeviceCount works in all the scenarios. As I've previously mentioned, my use case is very limited, I just want to be able to turn on and turn off Apple TV and TV with CEC.

Until there's a better solution, I will maintain a fork for my needs and maybe also other people will find it useful. I will also release a HASS plugin hopefully tomorrow that adapting the logicalDeviceCount power state.

P.S. Btw... New HASS Plugin version that you committed to HASS repo has an issue with Remote... homeassistant.components.remote doesn't have async_setup_entry, as a result, it's failing.

**Comment by stickpin** [comment]
HASS plugin with power state and on/off support.  https://github.com/stickpin/hass-atv-beta/

Here are the changes in case someone is interested: https://github.com/stickpin/hass-atv-beta/commit/601bc5413ae26b876f1c0dda2f8be30690c80851

**Comment by postlund** [comment]
> @postlund, totally agree with you, it's not possible to cover all the cases especially with old devices.
> In my case, I am only using ATV 4 and 4K with TVs connected over HDMI, so for me logicalDeviceCount works in all the scenarios. As I've previously mentioned, my use case is very limited, I just want to be able to turn on and turn off Apple TV and TV with CEC.

Yeah, that kinda makes it a problem for general inclusion in `pyatv` as it has to support it more generally 😄 I mean, it doesn't have to support it fully or all devices, but if it's not suppported then it has to be possible to get some information about it. I have a lot of functions that raises exceptions due to not being supported (by the device) but no way of giving an indication back to the user if they are supported. Only way to know is to call the methods and see if it raise or not. This is what #268 is supposed to fix. Implementing the solution we are discussing here would be possible if we knew if CEC is used or not, because then we could provide feedback about the state more properly.

> Until there's a better solution, I will maintain a fork for my needs and maybe also other people will find it useful. I will also release a HASS plugin hopefully tomorrow that adapting the logicalDeviceCount power state.

Sure, that can be a workaround for now. I'll see if I can improve on this. Maybe we can introduce a new state in the media player to make it work.

> P.S. Btw... New HASS Plugin version that you committed to HASS repo has an issue with Remote... homeassistant.components.remote doesn't have async_setup_entry, as a result, it's failing.

Nah, it's not an issue as that code is not supposed to be used as a custom component. Currently the remote component does not have support for config entries, but I added that with my PR. Once the PR is merged, then you can use that the code as a custom component again.

**Comment by postlund** [comment]
> HASS plugin with power state and on/off support. https://github.com/stickpin/hass-atv-beta/
> 
> Here are the changes in case someone is interested: [stickpin/hass-atv-beta@601bc54](https://github.com/stickpin/hass-atv-beta/commit/601bc5413ae26b876f1c0dda2f8be30690c80851)

There's a few issues here. You are breaking the API barrier by accesing `self.atv.push_updater.psm.powerState` as `psm` is private to the `MRP` protocol (see `interfaces.PushUpdate` for supported methods). This will break for `DMAP` devices both due to the fact that this code does not exists for that protocol but also because you cannot turn off those devices in that way.

You are also calling async methods from non-async code:

https://github.com/stickpin/hass-atv-beta/commit/601bc5413ae26b876f1c0dda2f8be30690c80851#diff-0352845707edb8cf50564667c04ca8b5R152

Same with `softdisconnect`. These calls must be scheduled on the even loop (with `self.hass.add_job`). It would also be better to implement the "soft disconnect" logic in the `disconnect` methods, to keep logic in one place. Ideally this code would move into `pyatv` instead, so the component wouldn't have to know about this at all.

**Comment by stickpin** [comment]
> > HASS plugin with power state and on/off support. https://github.com/stickpin/hass-atv-beta/
> > Here are the changes in case someone is interested: [stickpin/hass-atv-beta@601bc54](https://github.com/stickpin/hass-atv-beta/commit/601bc5413ae26b876f1c0dda2f8be30690c80851)
> 
> There's a few issues here. You are breaking the API barrier by accesing `self.atv.push_updater.psm.powerState` as `psm` is private to the `MRP` protocol (see `interfaces.PushUpdate` for supported methods). This will break for `DMAP` devices both due to the fact that this code does not exists for that protocol but also because you cannot turn off those devices in that way.

Actually I do have a Push Update in media_player.py and I do get updates during the "power state" change but not during the initial connect (for example when the HASS is restarted `powerstate_update` is not triggered and I don't know why. 

```
    @callback
    def powerstate_update(self, _, powerstate):
        """Handle when power state is changed."""

        if powerstate:
            self._manager._update_state(connected=True)
        else:
            self._manager._update_state(disconnected=True)

        self.async_schedule_update_ha_state()
```

> 
> You are also calling async methods from non-async code:
> 
> [stickpin/hass-atv-beta@601bc54#diff-0352845707edb8cf50564667c04ca8b5R152](https://github.com/stickpin/hass-atv-beta/commit/601bc5413ae26b876f1c0dda2f8be30690c80851#diff-0352845707edb8cf50564667c04ca8b5R152)
> 
> Same with `softdisconnect`. These calls must be scheduled on the even loop (with `self.hass.add_job`). 

It was the wrong code. :) See the code above. So, after all, it's a sync-to-sync call.

> It would also be better to implement the "soft disconnect" logic in the `disconnect` methods, to keep logic in one place. Ideally this code would move into `pyatv` instead, so the component wouldn't have to know about this at all.

I will see how to combine "disconnect" and "soft disconnect" together but I am not sure if I should, because two of them are representing two different flows.

- disconnect - is disconnecting from the device.
- soft disconnect - is keeping the connection and only visually changing the representation in HASS or Homekit based on the "power state" of ATV (on or standby) and in addition to that executing the "turn off" buttons sequence: `await self.atv.remote_control.home_hold()` and `await self.atv.remote_control.select()`

**Comment by stickpin** [comment]
Closing the issue in favor of proper power state implementation on pyatv itself.
More details [here](https://github.com/postlund/pyatv/pull/458)
