### ISSUE TITLE
ATVScript "playing" Command issues

### ISSUE THREAD

**Issue by villaocho** [postlund/pyatv#548]
**What feature would you like?**

Running the ATVSCRIPT command this is the output :

`{"result": "success", "hash": "75483FC0-ADD9-4666-A035-02FA44973FFB", "media_type": "video", "device_state": "playing", "title": "Bon Jovi - Live At Madison Square Garden", "artist": null, "album": "", "genre": null, "total_time": 8597, "position": 3109, "shuffle": "off", "repeat": "off"}`

**Describe the solution you'd like**

there seems to be a difference how the output is treated when no data is available in the fields : `null` or `empty field`

**Any other information to share?**

**Comment by postlund** [comment]
Yes and no. I've had the approach to report back whatever the device says and in this case the device returns an empty string as title, so that is why it is empty. The field itself (in the protocol message) is optional, so it could in theory been excluded. But I don't see any problems with changing this behavior in `atvscript` to replace empty strings with `None` (null) instead.

**Comment by postlund** [comment]
Created #549 which fixes this.
