### ISSUE TITLE
Protocol socket hangs after receiving large artwork

### ISSUE THREAD

**Issue by lucasec** [postlund/pyatv#609]
**Describe the bug**

When requesting large artwork images from the Apple TV, the protocol can sometimes completely hang up. No further state updates are sent, and no further commands from pyatv (play, pause) are processed.

There is likely something about the protocol we are missing. The Apple TV transmits a complete and valid artwork image, and only then does the connection hang. I found modifying messages.py I could get artwork sizes well over `-1` x `400`px, but these almost always guaranteed a hang. At 400, most content works, but some seems to fail intermittently.

**To Reproduce**

To re-produce this, I went to Netflix and attempted to watch "The Killing of a Sacred Deer". This produced a 135 KB artwork file, which triggered a hang reliably. Other Netflix content (such as "Better Call Saul" came in at 112 KB and did not trigger the hang.

I modified the code to request larger artwork sizes, and this also reliably triggered a hang with Music app cover images.

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: macOS
 - Python: 3.7.5
 - pyatv: 0.5.0
- Apple TV: Apple TV 4K tvOS 13.4 (17L256)

**Additional context**

Most likely there is something we're missing in the protocol—maybe some kind of acknowledgment we have to send. It's possible it's also a device bug.

Has anyone had luck using `atvproxy` to capture when control center requests artwork? This might be illuminating.

**Comment by lucasec** [comment]
I captured a PCAP as well, and happy to email that—but it does not reveal much. I see all artwork data transmitted and ACK'd by my machine, then the TCP stream just goes dark.

**Comment by postlund** [comment]
I know that there are some issues similar to this, i.e. the TCP sockets seems to just hang that I have not yet found any solution or reason for. But I have made a lot of changes on `master`, can you retry with that (if you haven't already)? Also, debug logs from `atvremote` and PCAP logs would be helpful. Be sure to run without MRP credentials, otherwise the traffic will be encrypted and hard to decode.

**Comment by lucasec** [comment]
I may have just found a possible fix via some random experimentation:

1. When we successfully receive artwork without a hang, the artwork comes in a SET_STATE_MESSAGE, followed by a TRANSACTION_MESSAGE of roughly the same size (presumably also containing the same artwork, but I don't understand transactions yet).

2. When we receive artwork that is too big and hangs, we get the SET_STATE_MESSAGE, but no TRANSACTION_MESSAGE. My theory is the Apple TV fails internally generating the transaction because it's too big/buffer overrun/etc.

3. By dumb luck, I found adding `returnContentItemAssetsInUserCompletion: true` to the PLAYBACK_QUEUE_REQUEST_MESSAGE suppresses generating the transactions, period. With this I've yet to encounter a hang.

This seemed to work for album art up to 1000px. For much larger than that, it returns an empty SET_STATE_MESSAGE with `sendingPlaybackQueueTransaction: true`. I then get multiple TRANSACTION_MESSAGEs with a large amount of data.

**Comment by lucasec** [comment]
Will pull master too and re-test, but that previous result seems promising.

**Comment by postlund** [comment]
Ok, so, that sounds interesting. Perhaps there's an upper size limit for messages that the protocol wants to send. Since a message is blocking in the sense that an entire message must be transferred in its entirety before other messages can be sent, it will potentially block other updates. The transaction message usually carry other messages, like the SET_STATE_MESSAGE when receiving artwork. So perhaps the device will split the payload over multiple transaction messages which can be multiplexed with other message, to avoid blocking updates for other things. That would at least be a reasonable thing to do.

It would be interesting to know what `returnContentItemAssetsInUserCompletion` *really* means. The naming is so verbose that it is cryptic...

Anyways, transactions is something that I have ignored for now so if something is only sent over transactions, then it won't work. Can you provide some debug logs for the different use cases you have tried?

**Comment by lucasec** [comment]
Here are a few logs—but you should be able to re-produce on your end without too much difficulty. I'm finding most video apps offer artwork that caps at a certain size, but the Music app is often willing to serve up larger images if you modify the requested size in `messages.py`.

There's four cases:

1. 400px height (the default currently in pyatv)—*without* the added `returnContentItemAssetsInUserCompletion = True` option. Notice here we see the artwork given to us in the SetStateMessage, but it also seems to give us a transaction too. This seemingly unnecessary transaction response seems to be what trips up the device at larger sizes.
2. 400px, this time with `returnContentItemAssetsInUserCompletion = True`. We only get the SetStateMessage.
3. 800px, with `returnContentItemAssetsInUserCompletion = True`. This was the request that reliably failed without the added request option.
4. 1200px with `returnContentItemAssetsInUserCompletion = True`. The SetStateMessage is interesting here in that it gives us no artwork, but sets `sendingPlaybackQueueTransaction = true` as a seemingly nice hint that it's gonna give us what we actually requested in a Transaction.

[log1-400px-withoutUserCompletion.log](https://github.com/postlund/pyatv/files/4519775/log1-400px-withoutUserCompletion.log)
[log2-400px-withUserCompletion.log](https://github.com/postlund/pyatv/files/4519776/log2-400px-withUserCompletion.log)
[log3-800px-withUserCompletion.log](https://github.com/postlund/pyatv/files/4519777/log3-800px-withUserCompletion.log)
[log4-1200px-withUserCompletion.log](https://github.com/postlund/pyatv/files/4519778/log4-1200px-withUserCompletion.log)

**Comment by lucasec** [comment]
Apple really has engineered the heck out of this—definitely one of the more interesting protocols I've seen in a while.

I haven't tried to decode the transaction data yet, but I suspect once all the packets are concatenated we probably get one of the existing protobufs.

**Comment by postlund** [comment]
Yeah, MRP is over engineered past every known border. But it also supports a *lot* of features, so I'm not surprised.

Trying to find some patterns regarding artwork sizes (roughly these sizes):
* 400px => 76K
* 800px => 415K
* 1200px => 1M

So, if the payload size is somewhere between 415K-1M, the device will not embed it into a single `SetStateMessage` response. My educated guess would be around 512K though, but lets call the tipping point X.

As long as the artwork size is less than X, the response `SetStateMessage` will contain the artwork. If above, `SetStateMessage` will indicate that the payload is split over several `TransactionMessage`s. The flag `sendingPlaybackQueueTransaction` will be set to `true` to signal this. The `requestId` field will match `transactionMessage->packets->packets->key->identifier`, so that is how we map them together.

Regarding `TransactionMessage`. The full payload length is included in every message via `totalLength`. Payload is in `packetData` and position in destination buffer is in `totalWritePosition`. So basically in some extreme pseudo-code (but this can be done in several ways of course):

```
buffer = byte[totalLength]
buffer[totalWritePosition:len(packetData)] = packetData
``` 

Sum of the length of `packetData` from all messages should of course sum up to `totalLength`. At least in theory the response could include artwork for several items, if there are more than one item in the playback queue. In that case we should match the content item `identifier` with what we are currently playing.

Anyways... Looking at the 1200px case. It is split over three `TransactionMessage` message, here is the second one:

```
2020-04-22 20:43:07 DEBUG: 10.4.1.13:57224<->10.4.1.45:49152 << Receive: Protobuf: type: TRANSACTION_MESSAGE
errorCode: NO_ERROR
[transactionMessage] {
  name: 9
  packets {
    packets {
      key {
        identifier: "19E307F7-8522-4980-AC91-595083E15C79"
      }
      packetData: "\333\262k\203v\277\272\211\316\243\252\333K\251I\035\274\321\277\220\3628\352\221I\023\270\330ct8\021\374\237?/\270\212\370\010P...
      identifier: "69668A88-3698-4F86-AC25-256CD599292C"
      totalLength: 1053847
      totalWritePosition: 500000
    }
  }
  playerPath {
    origin {
      type: Local
      displayName: "Workout Room Apple TV"
      identifier: 1280262988
    }
    client {
      processIdentifier: 161
      bundleIdentifier: "com.apple.TVMusic"
      processUserIdentifier: 501
      displayName: "Music"
    }
    player {
      identifier: "Music"
    }
  }
}
```

Since `totalWritePosition` is set to 500000, I assume that each part is 50kb (which matches my guess pretty good and we can probably set X=500000). The first two messages contains 500000 and the third and last one the remaining 53847 bytes.

Implementing support for concatenating all `TransactionMessage` messages is trivial, not many lines of codes. The tricky part is to handle this in the `artwork` method. Retrieving the artwork can take some time, so I guess a timeout would be needed. But how long would that be? Also, in general, how long should we cache the result of `TransactionMessage`s? Currently they only appear here, but perhaps we see them in other places later?

**Comment by postlund** [comment]
Testing a bit myself, I don't really see the same pattern. Not making any changes, except for size of artwork, I get this behavior:

* 400px => both `SetStateMessage` and one `TransactionMessage` containing artwork (size 53K)
* 800px => *only* a `SetStateMessage` containing the artwork (size 159K)
* 1200px => *only* a `SetStateMessage` containing the artwork (size 306K)
* 2400px => *only* a `SetStateMessage` containing the artwork (size 715K) - here the device restricts the size to 1400x2100px, so 2100px seems to be max size for this artwork

Same analysis but with `returnContentItemAssetsInUserCompletion` set to `true` yields the **exact same result** for me. No difference when this is set. Maybe it depends on what kind of media is playing? App? Not sure.

**Comment by lucasec** [comment]
Strange... I had a power outage this morning, and since I've been seeing slightly different behavior. `returnContentItemAssetsInUserCompletion` no longer seems to make a difference for me. I don't see any sign that I received a software update overnight ("About" shows same OS version and patch number).

At 800px mine was 415 KB. At 1000px, 702 KB. Both of these only came in `SetStateMessage`.

At 1200px, over 1 MB. This appears to be where the mandatory transactions start. At 2400px I could get mine to send me a 2 MB image.

I think the track I was using for testing is probably in those logs somewhere. If you happen to have an Apple Music subscription on hand perhaps you can try it.

**Comment by postlund** [comment]
Pushed the artwork size stuff now, will have to take a final look at it tomorrow. It's at #616 if you want to try it out.

**Comment by postlund** [comment]
Did we get any further on this? I'm not really sure where we left off and I do see a this a big issue. Some kind of solution would be good to get in place.

**Comment by lucasec** [comment]
I haven't had the time to invest more effort recently as things have been busier at my day job.

For a bit of context in my involvement with this library, I am developing a third-party integration driver for a certain commercial A/V control/universal remote system. It's written in old-style JS, but I certainly drew some inspiration from your code. While I don't have a ton of code that would be easy to contribute back directly, I'm certainly open to contributing back information and collaborating to try and document more protocol features.

I haven't seen any protocol hangs since adding `returnContentItemAssetsInUserCompletion` to my code. But I also had some difficulty re-producing the old problematic behavior when I tried removing that flag—so still not 100% sure what it does. With it there though the behavior is very consistent that I get a transaction if the returned data is large enough. I don't see my use cases typically needing large enough resolutions that the transaction gets triggered, but it might show up if there's a desire to request multiple tracks in a playback queue or something like that—so I may try my hand at a transaction implementation at some point.

Btw... not to go off subject, I also built an implementation for listing and selecting audio/subtitle languages. Can file some details on that off as a separate issue if helpful.

**Comment by postlund** [comment]
No worries, it's the same for me. I have a lot less time on my hands right now 😊 And I know for a fact that you are not the only commercial actor using pyatv (in one way or another, be it code inspiration or `atvproxy`), so I am not surprised 😉 The license does not prohibit it as long as no code is used (attribution is needed otherwise).

I'm always interested in documentation for new features. In general I find them easy to figure out with the proxy, but it's "convenient" if I don't have to do all the work. I have already put many, many hours into the project (especially the core parts). So anything you are willing to share, I'm thankful for! Documenting the protocol in the documentation is something I will try to take on at some point.

**Comment by lucasec** [comment]
Yup, sounds good. I'm also looking at whether I can decouple my own core apple TV-specific library from the platform SDK I am using (which is only offered under NDA)—in that case I would be able to open source some of the components. But I'm all for getting more protocol knowledge out in the open.

Btw—have you had any luck getting atvproxy to work with control center and the other iOS-integrated features? I've been trying to dig in a bit more on what's missing there, but no luck yet.

**Comment by postlund** [comment]
From my point of view are message definitions, flows, possible binary formats and quirks of more interest than an actual implementation (if that helps). Plotting the protocol specification for everyone to use should be the goal.

In iOS 13 Apple switched from using MRP in control center to use the companion protocol. I haven't found any information on the net about it, so I started reverse engineering it myself. See issue #655 and PR #657. It's just PoC and doesn't work, so I appreciate help in this department. There's some documentation about it in the PR.

**Comment by postlund** [comment]
I created #703 that I will use to implement transactions when I get some time. Maybe later today.

**Comment by lucasec** [comment]
re the companion protocol: Yikes... but good work on starting to decode the new protocol. It seems like control center still exhibits most of the quirks I've found within MRP, so hopefully most of the playback controls and feedback still use many of the same underlying messages. Also just opened https://github.com/postlund/pyatv/pull/704 to get started on language options.

**Comment by postlund** [comment]
Yeah, companion, *another* protocol... So far, only opening apps (and listing installed apps) are the main new feature we get with it. But I guess there's more. Playback feature are just relayed over to mediaremoted via XPC, so it's the same as using MRP but with additional layers.

Currently I'm kinda stuck. I'll see if I can get any further by just staring at it until it breaks, but I'm not so sure.

I will have a look at #704, can probably get the exact definitions for you.

**Comment by postlund** [comment]
I will add `returnContentItemAssetsInUserCompletion` tonight before making the 0.7.0 release. This should hopefully make it more stable, but will not work for larger payloads for now. I am working on transaction support, but it requires more work.

**Comment by postlund** [comment]
I at least haven't seen this, so I'm gonna close the issue. Somebody can re-open or create a new issue if it persists.

**Comment by lucasec** [comment]
I also haven't been able to re-produce this in a while. Wouldn't be surprised if recent tvOS updates quietly addressed the original bug where you could somehow get into a state that hangs the socket. Will open a new issue if I stumble across it again though.
