### ISSUE TITLE
Scan return no devices

### ISSUE THREAD

**Issue by radinsky** [postlund/pyatv#65]
Hey

I can ping appletv without problems but scan return no devices, what's wrong?

![image](https://cloud.githubusercontent.com/assets/4540268/24060274/32372f18-0b5b-11e7-83f5-2d9e74ff0fc3.png)

```
#
# ping 10.0.1.9
PING 10.0.1.9 (10.0.1.9) 56(84) bytes of data.
64 bytes from 10.0.1.9: icmp_seq=1 ttl=64 time=5.67 ms
64 bytes from 10.0.1.9: icmp_seq=2 ttl=64 time=4.44 ms
^C
--- 10.0.1.9 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 4.449/5.063/5.677/0.614 ms
# atvremote scan
Found Apple TVs:
# atvremote -t 9 scan
Found Apple TVs:
#
```

**Comment by postlund** [comment]
Scanning relies on bonjour, so that service must be working correctly. I'm gonna write a troubleshooting guide soon, but a few things you can check:
- Do you have home sharing enabled on your Apple TV? If not, enable that. In the next version of pyatv, you will be able to find devices without home sharing enabled as well (or if you just run from master)
- It is not supported to run atvremote in a container or virtual machine, it must be on the same network as the Apple TV
- I assume you run a mac, can you see the AirPlay capabilities (like screen mirroring)?
- If you have a firewall enabled, try disabling it while scanning. A fix will be provided for these situations soon.
- We have seen switching the Apple TV from WiFi to cable solves the problem
- You can try either ``dns-sd -B _appletv-v2._tcp`` or ``dns-sd -G -B _touch-able._tcp.``(on macOS) to see if it shows up

That's a few things I can think of.

**Comment by MetaImi** [comment]
For me disabling / enabling the home sharing solved the problem.

**Comment by postlund** [comment]
I believe this is fixed on `master`. Feel free to give it a try and report your founds in #214.
