### ISSUE TITLE
Volume controls are not working as expected for MRP

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#692]
**Describe the bug**
The volume controls are not working as expected. This was originally reported by @fmonday in #285 but this issue is created to lift out further discussions.

**To Reproduce**
Use `volume_up` or `volume_down` to change volume. Nothing happens.

**Expected behavior**
Volume increases/decreases.

**System Setup (please complete the following information):**
 - OS: any
 - Python: any
 - pyatv: any
- Apple TV: any with tvOS

**Additional context**
Intention is to use `atvproxy` to capture the traffic when changing volume and make adjustments after that.

**Comment by ckeehan** [comment]
This issue is interesting as volume control has always worked for me, both in the Remote app and with this implementation. So I did some digging and here is what I found...

The HID events that the MRP implementation is sending are the same ones sent by the iOS Remote app.

atvproxy event log for `volume_up`:
`Send raw (Data=080820006a3e0a3ccb66db14260b00000000000000000000010000000000000001000000200000000300000001000000000000000c00e900000000000000000001000000)`
https://github.com/postlund/pyatv/blob/688ec711f595f8271e91cfa375993dc0c9c0bb7c/pyatv/mrp/__init__.py#L65

atvproxy event log for `volume_down`:
`Send raw (Data=080820006a3e0a3c6cdead3a260b00000000000000000000010000000000000001000000200000000300000001000000000000000c00ea00000000000000000001000000)`
https://github.com/postlund/pyatv/blob/688ec711f595f8271e91cfa375993dc0c9c0bb7c/pyatv/mrp/__init__.py#L66

I also tried getting a mute capability to work which was requested [here](https://github.com/postlund/pyatv/issues/285#issuecomment-638847795). However, it seems this isn't yet supported by tvOS.

While I was at it, I went ahead and compared every HID event the MRP implementation sends to what the iOS Remote app sends. Interestingly, the key the Remote app sends for `home` and `home_hold` is different than what is used in the MRP implementation here. I'll create a pull request to clean that up.

**Comment by postlund** [comment]
That is interesting, perhaps you should try the volume keys again @fmonday? Maybe also include some debug logs so that we can see what the device reports.

Also, thanks a lot for verifying the HID values 👍 It was over two years ago that I looked at them (when implementing support for keys in the first place). So they were up for some review. Did you try all the various versions of mute HD codes and none of them worked, btw?

**Comment by postlund** [comment]
I tried to find if MRP exposed any mute capabilities, but seems to be a dead end. There is however a message for setting volume that I think looks something like this:

```
syntax = "proto2";

import "pyatv/mrp/protobuf/ProtocolMessage.proto";

extend ProtocolMessage {
  optional SetVolumeMessage setVolumeMessage = 55;
}

message SetVolumeMessage {
  optional float volume = 1;
  optional bytes outputDeviceUID = 2;
}
```

With constant `SET_VOLUME_MESSAGE = 51` in ProtocolMessage.proto.

Assuming we can figure out how to use it, we can implement mute but not unmute (of course). And also add the `set_volume` function. I believe there are some functionality for this in DMAP as well that could be added, just to align support. Just writing this for future reference...

**Comment by postlund** [comment]
I will close this since it's not really a problem anymore!
