### ISSUE TITLE
Possibility to set audio output like airplay, hdmi, ...

### ISSUE THREAD

**Issue by tgreve85** [postlund/pyatv#778]
It qould be great to set the audio outputs with your great api.
Always, when the atv starts, it streams sound out of the hdmi connector but I want to stream to my Sonos Play:5 via airplay.

Thank you for this powerful api!

**Comment by postlund** [comment]
That sounds like a good idea. I have no idea how external devices are handled protocol-wise. How are you changing output now? Via the sound menu? Or action center?

**Comment by tgreve85** [comment]
I am changing with long press on the tv button (top right) on the remote.
Then i scroll down tot he last icon in the menu.
Click it and there is by default my apple tv and under it my sonos play:5.
Then I select the play:5 and unselect the apple-tv.
Now the sound came over airplay in my home cinema with 5.1 surround 😉

Von: Pierre Ståhl <notifications@github.com>
Gesendet: Mittwoch, 22. Juli 2020 21:10
An: postlund/pyatv <pyatv@noreply.github.com>
Cc: Tim Greve <tgreve@stakotec.de>; Author <author@noreply.github.com>
Betreff: Re: [postlund/pyatv] Possibility to set audio output like airplay, hdmi, ... (#778)


That sounds like a good idea. I have no idea how external devices are handled protocol-wise. How are you changing output now? Via the sound menu? Or action center?

**Comment by tonysprenk** [comment]
Yes this would be an amazing feature. I have an AppleTV HD and HomePod. Since tvOS 14.2 AppleTV 4K and up support permanent audio output through HomePod but for anyone with an older AppleTV we have to select the output speaker manually every time we turn on the AppleTV. I am able to turn on my projector with the home app, it would be great to be able to maken an automation: when the projector turns on, turn on airplay switch. Where the airplay switch would be a switch in HA that through the magic of this great integrations changes the audio output of the AppleTV to a specified speaker. This would bring permanent audio support to older appleTV's

**Comment by shamanskyh** [comment]
Hi, thanks again for such a great library. I'm also interested in this feature in a more general sense (e.g. it'd be nice to trigger an automation that extends music playing from a HomePod in one room to a HomePod in another).

**Comment by postlund** [comment]
This is possible since 0.13.0.
