### ISSUE TITLE
tvOS sometimes handle remote control as long press

### ISSUE THREAD

**Issue by sy6sy2** [postlund/pyatv#792]
**Describe the bug**
During tvOS app development you can use `UITapGestureRecognizer` and `UILongPressGestureRecognizer` with, for example, `UIPressTypeUpArrow` press type to handle the up arrow key from remotes.

Take the Siri remote or the Apple TV remote on the iPhone with directional buttons enabled in accessibility. Each time you press the up arrow key you trigger `UITapGestureRecognizer` and only `UITapGestureRecognizer` regardless of the duration of the button hold.

Now take a random IR remote, add it in tvOS settings with the learning procedure. Again press the up key from this remote and see what what happen. You you do a simple press on the up button you will trigger `UITapGestureRecognizer`. You you hold the button more than `minimumPressDuration` you will trigger `UILongPressGestureRecognizer`.

Finally, take pyatv and send the `up` action with `await rc.up()`, sometimes tvOS trigger `UITapGestureRecognizer` and sometimes it will trigger `UILongPressGestureRecognizer` if you set `minimumPressDuration` with less than 1 second.

Do you know how pyatv handle the press duration notion? If yes, do you know how to fix pyatv in order to only have `UITapGestureRecognizer` trigger with `await rc.up()`, or, if it's possible, add an additional parameter in order to tell pyatv how many time the "button" need to be pressed.

**To Reproduce**
See Describe the bug**

**Expected behavior**
I expect `await rc.up()` (and other button) to simulate a simple "arrow tap" gesture in order to not randomly trigger `UILongPressGestureRecognizer`.

**System Setup (please complete the following information):**
 - OS: Raspberry Buster
 - Python: 3.7.3
 - pyatv: 0.7.0
- Apple TV: 4K tvOS 13.4.8 build 17M61

**Additional context:**
Thank you very munch for this project!
If you need to do some test, no problem for me.

**Comment by postlund** [comment]
This is an interesting view, since I don't really see the programmatic aspects in the protocol. Under the hood, sending a button press involves generating a HID event. It will contain things as which button is being considered, absolute mach time of the event and if it's press or release. So pressing a single button means sending two of the same event: one with press and one for release. There's a timing between those two, but of course also between the absolute times in the events. Currently I have just hardcoded a time in the events as I haven't decoded the time correctly. That might be the reason for this behavior, but I don't know.

The HID message is created here:

https://github.com/postlund/pyatv/blob/91de62f4c1e9e590b5971ded2104ce6f9140993d/pyatv/mrp/messages.py#L101

Pressing a button is implemented here:

https://github.com/postlund/pyatv/blob/91de62f4c1e9e590b5971ded2104ce6f9140993d/pyatv/mrp/__init__.py#L135

There's support for single tap, double tap and hold. By default single tap is used so that is what you should see when just calling for instance `up`. But I guess it's a bug somewhere in the HID data that we have to look at. Do you have any experience with IOKit and HID?

**Comment by sy6sy2** [comment]
Thank you for your fast reply. 

I didn't know that pyatv send two events for a single press. I guess you are right and the bug seems to come from the delta time that is to high between the press and the release event. 

Can I decrease this time somewhere to test? (I don't have my computer until next week). 

I don't have any experience in HID and only little experience with tvOS SDK. 
I am part of the Kodi team and I noticed this issue with Kodi because we have one function callback that handle single tap and another one that handle long single tap. And the single tap pyatv action randomly trigger the first function and the second one.

**Comment by postlund** [comment]
I only try to replicate the behavior of the remote app as much as possible and that's the way the app works (I have intercepted the traffic with `atvproxy`). There's no intentional delay between sending the two messages, so it should only depend on other factors (e.g. kernel and network latency). That's why I kinda suspect the time stamp in the events, since that time really tell the truth.

Not really sure that I follow your trail regarding kodi 😅 Do you have your own implementation or are you using pyatv somehow?

**Comment by sy6sy2** [comment]
If I understand correctly you compute the timestamp used for the release event simply by adding an hard coded value to the timestamp used in the press event?

Oh sorry, my english is horrible 😁. 
The long story is that I use pyatv on a RPI to "translate" keys press from an old IR remote into Apple TV remote control. This part is a personnal project.
The other is that I try to work on the Kodi project as a Kodi team member. And I noticed this bug but I didn't if pyatv or Kodi was faulty. After some test with the official Siri remote, the iOS Apple TV remote app and a second IR remote that directly control the Apple TV ; I was not able to reproduce the issue. This is why I am here because I think pyatv does something wrong that let the Apple TV thinking that the Single Tap of pyatv is a "too long" tap.

**Comment by postlund** [comment]
Sort of, but currently I don't compute any time stamp at all but just include a hard coded one. The same one for all events. I have not been able to decode the binary representation of the time, so I'm stuck with this until I figure that out... So, you can probably see why it could be problematic 😊

Ah, ok, so if I understand correctly, this is why you see in the Kodi *app* running on your Apple TV? Then I can understand your concerns here 😊

**Comment by sy6sy2** [comment]
Oh ok ; and the Apple TV doesn't care about this fake timestamp? 0_o

Oh yes sorry, I miss this part on my original message but Kodi is running on the Apple TV and I am testing if Kodi perform "normal" behaviour if I control it from pyatv events. 
I check if a specific action from the Siri remote and from pyatv produces the same result/behaviour in Kodi.

**Comment by postlund** [comment]
Yeah, it seems to ignore it 😉

Ah, right. Then I understand 👍

**Comment by postlund** [comment]
I've spent some additional time trying to understand the time stamp, but I'm kinda stuck. There's another, simplified protobuf message for sending button presses though,  `SEND_BUTTON_EVENT_MESSAGE`, that maybe can help. It was implemented in #799, but has to be extracted and verified to work first. But maybe you can help out with that once it's finished?

**Comment by sy6sy2** [comment]
Thank you for the time you spent on this!
For sure I can test any PR if needed. This one is currently closed but let me know if you need me to test something!

**Comment by postlund** [comment]
Sure thing! I will try to work on it as soon as I can. If possible, draft a PR tonight for testing purposes at least.

**Comment by postlund** [comment]
So, I have created #808 as PoC. I tried it out on my Apple TV and functionality-wise it seems to work. Please give it a spin and let me know if it works better 😊

**Comment by sy6sy2** [comment]
Thank you for this poc. Unfortunately I have the same issue 😕

**Comment by postlund** [comment]
Damn it, was hoping that would work 😕 The only thing I can think of now is to dump the traffic with atvproxy and try to figure out what is different to what I'm doing now. Start by setting up atvproxy, it's described [here](https://pyatv.dev/documentation/atvproxy/#mrp-proxy).

Once the proxy is set up and you have paired, just trigger a single tap left (or something similar). Just to keep unnecessary stuff out from the log.

**Comment by postlund** [comment]
I will close this now, please re-open if you see an urgent need for trying to fix this again.
