### ISSUE TITLE
Is the Series Title available for Shows?

### ISSUE THREAD

**Issue by 0evmc** [postlund/pyatv#793]
Running pyATV in Home Assistant - I've noticed that the primary title for a **movie** is usually the _movie title_ (which is enough for a movie), and the primary title for a **TV show** is the _episode title_ (which is great, but not enough information). If you visually look at the entity picture generated, you can usually tell what TV show is being played, but there is no way to capture that via simple text. 
**If you look at the screenshot below, there is no way to know what TV Show is being played**. 
I am wondering if there is a different field offered that the pyATV integration is not utilizing yet or whether the AppleTV simply does not offer up that information anywhere.  If the information is available somewhere, it would be an excellent feature to capture that data.
<img width="424" alt="Screen Shot 2020-08-13 at 9 55 15 AM" src="https://user-images.githubusercontent.com/48167222/90143596-cf64d900-dd4b-11ea-8c89-d1dee9d7a839.png">

**Comment by postlund** [comment]
This is a good point. Currently `pyatv` supports album, artist, genre, media type and title. Only title and media type is implemented at the moment, but adding the remaining fields should be simple. The biggest culprit however is that each app is responsible for providing the correct metadata, but a lot of them don't. IIRC Netflix for instance does not (only title there). So even when implemented, it can be of limited use because of limited support in the app. Just want to mention that.

https://pyatv.dev/api/interface#pyatv.interface.Playing

**Comment by postlund** [comment]
This file declares what can be theoretically available btw:

https://github.com/postlund/pyatv/blob/master/pyatv/mrp/protobuf/ContentItemMetadata.proto

But as I said, it depends on the app and most of just provides the most basic metadata.

**Comment by postlund** [comment]
Great news, this PR will add these fields:

https://github.com/home-assistant/core/pull/61107

Won't be available in official Home Assistant until January release, but it is available in the beta component (but you need Home Assistant 2021.12.x beta to run it).

**Comment by postlund** [comment]
Merged to core so this is done.
