### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by robbiet480** [postlund/pyatv#8]
So what are your thoughts on implementing `playstatusupdate`?

**Comment by postlund** [comment]
Technically ``playstatus`` is already used in the "polling" interface. What is needed is to add the correct revision-id, so that it blocks and wrap some nice interface around it. I would rank it high on my priority list and plausible for 0.2.0 or so. Maybe we can use this issue to discuss the API a bit since I haven't thought about that yet.

**Comment by postlund** [comment]
Implemented in #52 .
