### ISSUE TITLE
Installed i HACS and got two (2) ATV integrations !

### ISSUE THREAD

**Issue by oywino** [postlund/pyatv#805]
I installed the custom component as described, and somehow I ended up having 2 almost identical integrations. Since integrations now are shown only as icons (cards) and not as a list, I cannot see the complete name of the second instance, but the first one says:
`Apple TV: Apple TV` while the second says `Apple TV: Apple TV (Ho...`
Which one of the two (almost) identical integrations should I use?
What is the the missing part of the heading, beginning with (Ho...  ?

I'm running HA 0.114.2 in a docker container on a QNAP NAS
I have a single ATV Gen 2 device.

**Comment by postlund** [comment]
Yes, I agree that this is confusing and I should really do something about it. When you have activated home sharing on your Apple TV, an identifier called `hsgid` is provided by the device in the scanning result. This identifier can be used to control the Apple TV without having to perform a pairing process (which is the other way to control the device). This is of course nice, but I have seen problems when other apps use the same identifier. It causes some kind of conflict and works poorly, so using `hsgid` is not a good choice and pairing should be preferred since that yields a new unique identifier.

So, the missing text reads "Home Sharing" and I recommend to use the other one instead because of the reason above.

**Comment by oywino** [comment]
Great! :-)
Thanks for the quick reply.
By the way, is it possible (and safe) to get rid of (delete/remove) the unwanted one, from appearing at all?

**Comment by postlund** [comment]
If you add the "other" Apple TV, the "Home Sharing" version should hopefully disappear automatically. They map to the same "device", so it should not be picked up again. I don't discard it manually, so you might have to restart Home Assistant though.

**Comment by postlund** [comment]
I removed the "Home Sharing" discovery I the latest update, so hopefully this should not be a problem anymore. If you could try it out it would be great (basically remove the integration, wait for it to be auto-discovered again).

**Comment by postlund** [comment]
I assume this to be fixed, so I will close the issue now.
