### ISSUE TITLE
python-miio ERROR messages

### ISSUE THREAD

**Issue by oywino** [postlund/pyatv#819]
I'm running HA Core 0.114.2 in a docker container.
I have an ATV Gen 3.
After successfully installing the ATV beta integration, I tried to install the pyatv, and got the following error messages:

```
ERROR: python-miio 0.5.3 has requirement construct<3.0.0,>=2.10.56, but you'll have construct 2.9.45 which is incompatible.

ERROR: python-miio 0.5.3 has requirement pytz<2020.0,>=2019.3, but you'll have pytz 2020.1 which is incompatible.

ERROR: python-miio 0.5.3 has requirement zeroconf<0.26.0,>=0.25.1, but you'll have zeroconf 0.28.1 which is incompatible.

ERROR: aioesphomeapi 2.6.1 has requirement protobuf==3.6.1, but you'll have protobuf 3.12.2 which is incompatible.
```

So, what does this mean - and what do I do ?

**Comment by postlund** [comment]
One thing I noted is that zeroconf has been bumped to a higher required version in pyatv, which is wrong. I will fix that today hopefully. The other errors I don't know. I feel that I know to little about your setup and what you are trying to do?

**Comment by oywino** [comment]
So far, I'm not trying to do anything - except install whatever needs to be installed before I attempt to do something.
I installed your ATV beta integration using HACS, did the configuration successfully, and then jumped into the container and typed;

`pip3 install pyatv`

That's when I got the mentioned eror messages.

**Comment by postlund** [comment]
What do you need pyatv for in this case? It will be installed automatically by Home Assistant. If you need to use for instance `atvremote` or develop something with `pyatv`, I strongly suggest that you use another environment for that. Perhaps one of the official python containers.

**Comment by oywino** [comment]
Oops,  There you go - how difficult it sometime is to follow "user-guides".  I just read, and clicked on a link and landed on a "Getting Started" that said to install `pyatv `in order to use `atvremote` (whatever that is).  And so I did.  Not did I know that `pyatv` was already installed with HA - in fact, I have no idea what `pyatv `is.
I just assumed that `atvremote ` was _something_ that would enable me to easily make an AppleTV remote control LoveLace card. 
So - that's what I want to have; An easy solution to quickly get a GUI card with the necessary icons needed to control my AppleTV  :)   Just as the real physical AppleTV remote control.

**Comment by postlund** [comment]
`pyatv` is just a library used to interact with an Apple TV and the beta component uses it to add support for that to Home Assistant. As it is a dependency, home Assistant will install it automatically when needed. It does come with `remote` support, but no Lovelace card. Since home Assistant does not have any notion of remote buttons (just a generic interface to send button presses), there's to way to create a "generic" remote control. You will have to resort to 3rd party cards or build something yourself. You can probably find some inspiration in the community forums, like this one for instance:

https://community.home-assistant.io/t/apple-tv-remote-implementation/194317/2

**Comment by oywino** [comment]
Thank you so much!  I'll give that one a try :)

**Comment by postlund** [comment]
I'll close this one now, just re-open if you have any additional questions!
