### ISSUE TITLE
Migrating from HACS to HA 2020.12

### ISSUE THREAD

**Issue by curt7000** [postlund/pyatv#894]
@postlund - Great work with this!  Just curious, what is the recommended approach to move to 2020.12 now that this is included in HA Core?  Thanks!

**Comment by postlund** [comment]
There are a few things in the beta repo that is not part of Home Assistant core yet, "device" support being one of them. I intend to fix that soon, so that the features match up. Hopefully this will be in the 2021.01 release. After that I will just copy what is in core, put it in `hass-atv-beta` and make a release and it should work fine to be either on the beta repo or the built in version. But until then you can stay on the beta component if you like. As the nothing has changed config-wise, they are compatible with each other.

**Comment by curt7000** [comment]
Thanks!
